### ISSUE TITLE
When using AddCredentials option no public constructors are available

### ISSUE THREAD

**Issue by dicko2** [Azure/autorest#628] opened 2016-01-20 05:25 UTC
My issue is that when using the addCredentials Command line option with CSharp, none of the constructors are public, they are all protected.

At first i thought it maybe because some were marked as internal so tried adding the option x-ms-code-generation-settings/internalConstructors to false in the json, however this didn't work and on expecting the generated C# code i can see that not even internal constructors are present.

Using a b asic example i should be able to do this

    namespace ConsoleApplication1
    {
    class Program
    {
        static void Main(string[] args)
        {
            var svc = new MyWebAPI();
            svc.BaseUri = new Uri("http://MyWebAPI.dev.net/v2.0");
            svc.Credentials= new BasicAuthenticationCredentials{UserName = "UserName",Password = "Pa$$w0rd"};
            Console.WriteLine(svc.HelloWorld());
            Console.ReadLine();
        }
    }
    }

But instead i am forced to do this

    namespace ConsoleApplication1
    {
    class Program
    {
        static void Main(string[] args)
        {
            var svc = new MyClient();
            svc.BaseUri = new Uri("http://MyWebAPI.dev.net/v2.0");
            svc.Credentials= new BasicAuthenticationCredentials{UserName = "UserName",Password = "Pa$$w0rd"};
            Console.WriteLine(svc.HelloWorld());
            Console.ReadLine();
        }
    }
    }

    public class MyClient : MyWebAPI
    {
    public MyClient() :base()
    {
        
    }
    }

I believe the file that needs to change is here
\AutoRest\Generators\CSharp\CSharp\Templates\ServiceClientBodyTemplate.cshtml

line 49, 64, 79, 102

The string should be changed to public and not be protected. 

Regards,
Joel

**Comment by ingAlfano** [comment] 2016-01-22 09:12
Hi, this is a duplicate of issue https://github.com/Azure/autorest/issues/570
 this should be fixed in pull https://github.com/Azure/autorest/pull/592

**Closed** 2016-01-22 18:53 UTC
Labels: duplicate
