### ISSUE TITLE
[Feature Request] Warn on out of date node runtime

### ISSUE THREAD

**Issue by chamons** [Azure/autorest#4079] opened 2021-04-16 14:15 UTC
**Is your feature request related to a problem? Please describe.**
Yesterday a coworker ran into this error:

```
(node:22400) UnhandledPromiseRejectionWarning: Error: UNKNOWN: unknown error, open 'PATH\CodeModel.yaml'
(node:22400) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 103)
```

which is very difficult to parse.

It turns out she was using node 12.18 and updating to node 14 solved it.

**Describe the solution you'd like**

Would it be possible in our crash handler to detect ancient node versions and add some text like "You are using node X and node Y is recommended. Consider downloading an update from https://nodejs.org/en/download/.`

**Describe alternatives you've considered**
Do nothing, and catch these on Teams still.

**Comment by timotheeguerin** [comment] 2021-04-16 14:56
It should warn you if you use node 10 or below but node 12 should be supported.

**Comment by chamons** [comment] 2021-04-16 15:28
See [conversation](https://teams.microsoft.com/l/message/19:acbd512e57bd475198ea6bf4564599e3@thread.skype/1618528665709?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=3e17dcb0-4257-4a30-b843-77f47f1d4121&parentMessageId=1618528665709&teamName=Azure%20SDK&channelName=AutoRest%20-%20CSharp&createdTime=1618528665709) for example.

**Comment by timotheeguerin** [comment] 2021-04-20 18:12
Closing as duplicate of #4090

**Closed by timotheeguerin** 2021-04-20 18:12 UTC
