### ISSUE TITLE
Support Swagger Doc v3.0

### ISSUE THREAD

**Issue by AmirSasson** [Azure/autorest#4385] opened 2021-12-07 09:49 UTC
Swagger 3.0 is currently not supported by AutoRest,
this requires us to make some hackings when it come to inheritance of definitions  

i would like AutoRest to support Swagger docs 3.0

![image](https://user-images.githubusercontent.com/11300892/145006187-023108ed-b78a-40cf-b424-87eb3f7fc9fc.png)

**Comment by timotheeguerin** [comment] 2021-12-07 16:40
Duplicate of https://github.com/Azure/autorest/issues/4118?

**Closed by timotheeguerin** 2021-12-07 16:40 UTC
Labels: duplicate
