### ISSUE TITLE
CSharp client generation failing using autorest --version=3.0.6282

### ISSUE THREAD

**Issue by gegilin** [Azure/autorest#3524] opened 2020-06-24 17:41 UTC
Hi,

Encountered on an issue using the latest version of autotest client v3.0.6282( all previous versions worked perfectly) when tried to generate sharp client code from swagger JSON(attached) generated by Swashbuckle 5.5.0. Tried to use 

 autorest --version=3.0.6282 --csharp --input-file=c:\tmp\apispec.core.audit.2020-03-01-preview.json --output-folder=./audit/

```
{
  "openapi": "3.0.3",
  "info": {
    "title": "",
    "version": ""
  },
  "paths": {
    "/api/audit": {
      "get": {
	  }
	}
  },
  "components": {
    "schemas": {
      "CallerIdentityType": {
        "enum": [
          "Name"
        ],
        "type": "string"
      },
      "CallerIdentity": {
        "type": "object",
        "properties": {
          "callerIdentityType": {
            "$ref": "#/components/schemas/CallerIdentityType"
          },
          "callerIdentity": {
            "type": "string",
            "nullable": true
          }
        },
		"additionalProperties": false
      }
    }
  }
}
```

`FATAL: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.CallerIdentity.additionalProperties', line 1, position 10186.
FATAL: AutoRest.Core.Logging.CodeGenerationException: Error parsing swagger file. Error converting value False to type 'AutoRest.Modeler.Model.Schema'. Path 'components.schemas.CallerIdentity.additionalProperties', line 1, position 10186.
   at AutoRest.Modeler.SwaggerParser.Parse(String swaggerDocument) in /opt/vsts/work/1/s/src/SwaggerParser.cs:line 52
   at AutoRest.Modeler.Program.<ProcessInternal>d__2.MoveNext() in /opt/vsts/work/1/s/src/Program.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__15.MoveNext()
  Error: Plugin imodeler1 reported failure.`

P.S. Tried to use another [client ](https://mvnrepository.com/artifact/io.swagger.codegen.v3/swagger-codegen-cli/3.0.20)and all worked smoothly with the same JSON
~~~
java -jar .\swagger-codegen-cli-3.0.20.jar generate -i c:\tmp\apispec.core.audit.2020-03-01-preview.json  -l csharp -o csharp_client
~~~

**Comment by ohadschn** [comment] 2020-08-26 15:00
Looks like a duplicate of https://github.com/Azure/autorest/issues/3492

**Comment by daviwil** [comment] 2020-10-08 22:42
Thanks @ohadschn, closing as duplicate of #3492.

**Closed by daviwil** 2020-10-08 22:42 UTC
