### ISSUE TITLE
Problem for generating C# client: "System.NotSupportedException: Collection format None is not supported.

### ISSUE THREAD

**Issue by spywen** [Azure/autorest#2669] opened 2017-10-24 12:35 UTC
Hello guys, 
I met a problem in order to generate a client thanks to autorest... 
Actually, I have correct swagger json definition (validated on online swagger editor -> 2.0.0) BUT
An error is raised: 
```
[14:26:57] Network Enabled: true
[14:26:58] The most recent installed version is 2.0.4168
[14:26:58] latest was not satisfied directly by a previous installation.
[14:26:58] Selected package: @microsoft.azure/autorest-core@2.0.4168 => ^2.0.4166
[14:26:58] AutoRest Core 2.0.4168 is available at C:\Users\lbabin\.autorest\@microsoft.azure_autorest-core@2.0.4168\node
_modules\@microsoft.azure\autorest-core
[14:26:58] Starting @microsoft.azure/autorest-core from C:\Users\lbabin\.autorest\@microsoft.azure_autorest-core@2.0.416
8
[14:26:58] Using core from: "C:\Users\lbabin\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.a
zure\autorest-core"
WARNING: The parameter --debug looks like it was meant for the new CLI! Note that you have invoked the legacy CLI (by us
ing at least one single-dash argument). Please visit https://github.com/Azure/autorest/blob/master/docs/user/cli.md for
information about the new CLI.
WARNING: The parameter --allow-no-input looks like it was meant for the new CLI! Note that you have invoked the legacy C
LI (by using at least one single-dash argument). Please visit https://github.com/Azure/autorest/blob/master/docs/user/cl
i.md for information about the new CLI.
FATAL: System.NotSupportedException: Collection format None is not supported.
   at AutoRest.CSharp.ClientModelExtensions.GetSeparator(CollectionFormat format) in C:\Users\ci\AppData\Local\Temp\PUBL
ISHv6236\30_20171011T220809\autorest.csharp\src\vanilla\ClientModelExtensions.cs:line 235
   at AutoRest.CSharp.ClientModelExtensions.GetFormattedReferenceValue(Parameter parameter, String clientReference) in C
:\Users\ci\AppData\Local\Temp\PUBLISHv6236\30_20171011T220809\autorest.csharp\src\vanilla\ClientModelExtensions.cs:line
210
   at AutoRest.CSharp.Model.MethodCs.BuildUrl(String variableName) in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\30_201
71011T220809\autorest.csharp\src\vanilla\Model\MethodCs.cs:line 389
   at AutoRest.CSharp.vanilla.Templates.Rest.Client.MethodTemplate.<ExecuteAsync>d1.MoveNext() in C:\Users\ci\AppData\Lo
cal\Temp\PUBLISHv6236\30_20171011T220809\autorest.csharp\src\obj\Razor\vanilla\Templates\Rest\Client\MethodTemplate.csht
ml:line 120
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.Template"1.ToString()
   at AutoRest.CSharp.vanilla.Templates.Rest.Client.ServiceClientTemplate.<ExecuteAsync>d1.MoveNext() in C:\Users\ci\App
Data\Local\Temp\PUBLISHv6236\30_20171011T220809\autorest.csharp\src\obj\Razor\vanilla\Templates\Rest\Client\ServiceClien
tTemplate.cshtml:line 101
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.Core.CodeGenerator.<Write>d12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateClientSideCode>d8.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv62
36\30_20171011T220809\autorest.csharp\src\vanilla\CodeGeneratorCs.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<GenerateRestCode>d9.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\30_
20171011T220809\autorest.csharp\src\vanilla\CodeGeneratorCs.cs:line 124
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.CodeGeneratorCs.<Generate>d10.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\30_2017101
1T220809\autorest.csharp\src\vanilla\CodeGeneratorCs.cs:line 157
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at AutoRest.CSharp.Program.<ProcessInternal>d4.MoveNext() in C:\Users\ci\AppData\Local\Temp\PUBLISHv6236\30_20171011T
220809\autorest.csharp\src\Program.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d15.MoveNext()
FATAL: csharp/generate - FAILED
FATAL: Error: Plugin csharp reported failure.
Process() Cancelled due to exception : Plugin csharp reported failure.
Error: Plugin csharp reported failure.
    at CreatePluginExternal (C:\Users\lbabin\.autorest\@microsoft.azure_autorest-core@2.0.4168\node_modules\@microsoft.a
zure\autorest-core\dist\lib\pipeline\pipeline.js:91: 19)
    at <anonymous>
PS D:\ITESSO\Grammar\Json\Booking>
```

As you can see the problem is : "System.NotSupportedException: Collection format None is not supported.". 
Do you have an idea? 
Thanks for your time :)

**Comment by spywen** [comment] 2017-10-24 12:38
Note: I'm able to generate a client from Swagger-editor...

**Comment by fearthecowboy** [comment] 2017-10-24 15:42
Hey @spywen ,

We'd need to see the swagger, and the command line that you actually used.

You've got at least one parameter with single dash (you probably meant `--`).

And then on top of that, I'm guessing you've probably got a `collectionFormat: None` -- which would be on an array for a query parameter, which doesn't tell us how to parse a collection.

**Comment by spywen** [comment] 2017-10-26 11:32
Hello,
Sorry I can't share the whole swagger file (legal issue)
Finally i found the origin of the problem:
`
"itemCodes": {
      "name": "item_codes",
      "in": "query",
      "required": true,
      "description": "Example: item_codes=I1,I2,I3",
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1,
        "maxLength": 8
      }
    },
`
It failed because of this definition which is an URL parameter.
So just by changing type to string: i solved the problem by entering manually a string with part "comma separated". 
But: this syntax is a valid syntax for swagger.
Is there an issue with Autorest here? Or did i miss something?

**Comment by fearthecowboy** [comment] 2017-10-27 15:31
The issue is that if you specify the query parameter as `type:array`, you have to tell autorest how the items are formatted. Add `"collectionFormat": "csv" ` to the parameter definition.

Hmm. according to https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameter-object -- `csv` is the default. Clearly, that's not what we're doing.

That's a bug!

(still, add the `"collectionFormat": "csv" ` to the parameter definition to work around it)

**Comment by spywen** [comment] 2017-10-31 08:52
Hello, thanks a lot for you response. 
Sorry, I'm not enough familiar with Github but: is it plan to fix this point? 
Do I need to do something else than raised this issue? 
Thanks again for your time :+1:

**Comment by fearthecowboy** [comment] 2017-10-31 14:21
I don't have time to fix this right away.

To work around it add `"collectionFormat": "csv"` to the parameter definition.

**Comment by spywen** [comment] 2017-10-31 16:23
Yes yes no problem. I did it :+1: It was working fine :) 
But just to have an idea: when can we expect to have the fix ? 1 week, 1 month, one year?

**Comment by MiYanni** [comment] 2019-11-07 00:39
Workaround provided. Closing.

**Closed by MiYanni** 2019-11-07 00:39 UTC
