### ISSUE TITLE
Link not working for ref to autorest.csharp doc on how to use the generated client.

### ISSUE THREAD

**Issue by KristofferStrube** [Azure/autorest#4031] opened 2021-04-01 17:23 UTC
**Describe the bug**
On this page [https://github.com/Azure/autorest/blob/master/docs/client](https://github.com/Azure/autorest/blob/master/docs/client) the link to the documentation for C# is not working.

**Expected behavior**
It is expected that it references the documentation for how to use the generated C# client. This is especially important because of the new AutoRest V3 generator. On this page: [https://github.com/Azure/autorest/tree/master/docs/generate](https://github.com/Azure/autorest/tree/master/docs/generate) it states that one can find information especially about `"how to authenticate to our generated clients"` on the page that is not linked correctly.

**Additional context**
I don't know if this documentation actually exists for AutoRest.CSharp.

**Comment by timotheeguerin** [comment] 2021-04-01 17:44
Duplicate of #4020

**Closed by timotheeguerin** 2021-04-01 17:44 UTC
Labels: Bug
