### ISSUE TITLE
Failed to install or start extension '@autorest/python' (latest)

### ISSUE THREAD

**Issue by 93mishra** [Azure/autorest#3915] opened 2021-02-23 17:31 UTC
**Describe the bug**
Tried to generate connectedvsphere python sdk through autorest on Windows but getting error:  Failed to install or start extension '@autorest/python' 

Please provide as much information as you can. This would be: 

autorest azure-rest-api-specs-pr\specification\connectedvmwarevsphere\resource-manager\readme.md --python --python-sdks-folder=azure-sdk-for-python --python-mode=update
...
...
...
{"type":"step","data":{"message":"Building fresh packages","current":4,"total":4}}
{"type":"error","data":"C:\\Users\\sanmishra\\.autorest\\@autorest_python@5.6.3\\node_modules\\@autorest\\python: Command failed.\nExit code: 1\nCommand: node run-python3.js install.py\nArguments: \nDirectory: C:\\Users\\sanmishra\\.autorest\\@autorest_python@5.6.3\\node_modules\\@autorest\\python\nOutput:\nError: Failed to find compatible python version. Couldn't find a valid python interpreter satisfying the requirement (version: >=3.6). Tried:\n - py ('py' command line is not found in the path. Make sure to have it installed.)\n - python3 (Couldn't parse the version . This is not a valid semver version.)\n - python (Couldn't parse the version . This is not a valid semver version.)"}
{"type":"info","data":"Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command."}
--------------------------------------------------
Failed to install or start extension '@autorest/python' (latest)
  Error: Package '@autorest/python' - '5.6.3' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/python/-/python-5.6.3.tgz' -- Error: Process Failed.Error: Failed to install package 'https://registry.npmjs.org/@autorest/python/-/python-5.6.3.tgz' -- Error: Process Failed.
    at Yarn.install (C:\Users\sanmishra\.autorest\@autorest_core@3.0.6375\node_modules\@autorest\core\dist\src_lib_autorest-core_ts.js:14768:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)

- OpenAPI files having the issues
- Autorest command used
autorest azure-rest-api-specs-pr\specification\connectedvmwarevsphere\resource-manager\readme.md --python --python-sdks-folder=azure-sdk-for-python --python-mode=update

**Expected behavior**
python sdk should get generated. 

**Additional context**
No

**Comment by timotheeguerin** [comment] 2021-02-23 18:02
Hi, do you have python 3.6 or more installed? if so could you share the result of `python --version`

**Comment by trebconnell** [comment] 2021-02-23 21:10
I am also reproducing similar issue with csharp.
If I use flag ```--version=3.0.6320``` the issue is resolved.

Full output without --version:
```
AutoRest code generation utility [cli version: 3.1.1; node: v14.15.5, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
NOTE: AutoRest core version selected from configuration: ~3.0.6298.
   Loading AutoRest core      'C:\Users\treb\.autorest\@autorest_core@3.0.6375\node_modules\@autorest\core\dist' (3.0.6375)
Failed to install or start extension '@autorest/csharp' (latest)
  TypeError: Cannot read property 'startsWith' of undefined
```

**Comment by timotheeguerin** [comment] 2021-02-23 22:04
@trebconnell I believe your issue is a different problem that has been resolved in the latest preview version. You could try `--version=3.1.0-dev.2`

**Closed** 2021-03-24 19:59 UTC
Labels: Bug

**Comment by felixvd** [comment] 2021-11-24 01:21
I am having a similar problem. I am on Debian 9 and the highest Python version available via binaries is 3.5.4 . After building Python from source (following these instructions and `sudo make install` instead of `make altinstall`), `autorest` is not able to parse the version number returned by `python3` anymore. 

Here is the log:

```
$ sudo autorest --input-file=api.yml --python
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v16.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/root/.autorest/@autorestcore@3.7.1/nodemodules/@autorest/core/dist' (3.7.1)
info    |    Installing AutoRest extension '@autorest/python' (latest -> 5.11.2)
installing... [========================================] 100% | 918/918
error   |   Error: Package '@autorest/python' - '5.11.2' failed to install:
  Failed to install package 'https://registry.npmjs.org/@autorest/python/-/python-5.11.2.tgz' -- Error: Process Failed.

Installation logs: 

  | warning: package.json: No license field
  | info: No lockfile found.
  | info:  Step: Resolving packages
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > libcipm@4.0.8: This module is no longer used. Please see @npmcli/arborist if you would like to build and reify package trees programmatically.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
  | warning: https://registry.npmjs.org/ > @azure-tools/extension > npm > request > har-validator@5.1.5: this library is no longer supported
  | info:  Step: Fetching packages
  | info:  Step: Linking dependencies
  | info:  Step: Building fresh packages
  | error: /root/.autorest/@autorestpython@5.11.2/nodemodules/@autorest/python: Command failed.
  |        Exit code: 1
  |        Command: node run-python3.js install.py
  |        Arguments: 
  |        Directory: /root/.autorest/@autorestpython@5.11.2/nodemodules/@autorest/python
  |        Output:
  |        Error: Failed to find compatible python version. Couldn't find a valid python interpreter satisfying the requirement (version: >=3.6). Tried:
  |         - python3 (Couldn't parse the version . This is not a valid semver version.)
  |         - python ('python' version is '2.7.13' but doesn't satisfy requirement '>=3.6'. Please update.)
  | info: Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

fatal   | Failed to install extension '@autorest/python' (latest)
$ python -c "import sys; print('.'.join(map(str, sys.version_info[:3])))"
2.7.13
$ python3 -c "import sys; print('.'.join(map(str, sys.version_info[:3])))"
3.7.0
```

When I don't supply an input file, I am told that `@autorest/python` was installed (as per the log below), but the results in the log above don't change.

```
$ autorest --python
SourceMapConsumer.initialize is a no-op when running in node.js
AutoRest code generation utility [cli version: 3.5.1; node: v16.13.0]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
info    | AutoRest core version selected from configuration: ^3.7.0.
SourceMapConsumer.initialize is a no-op when running in node.js
info    |    Loading AutoRest core      '/home/mujin/.autorest/@autorestcore@3.7.1/nodemodules/@autorest/core/dist' (3.7.1)
info    |    Installing AutoRest extension '@autorest/python' (latest -> 5.11.2)
installing... [========================================] 100% | 918/918
info    |    Installed AutoRest extension '@autorest/python' (latest->5.11.2)
info    |    Installing AutoRest extension '@autorest/modelerfour' (~4.19.1 -> 4.19.3)

info    |    Installed AutoRest extension '@autorest/modelerfour' (~4.19.1->4.19.3)
error   | [Exception] No input files provided.

Use --help to get help information or see https://aka.ms/autorest/cli for additional documentation
error   |   Error: [Exception] No input files provided.

Use --help to get help information or see https://aka.ms/autorest/cli for additional documentation
```

How can I proceed with debugging this? The Python version seems healthy to me.

**Comment by timotheeguerin** [comment] 2021-11-24 01:50
This is weird, specially as this seems to have installed the extension just fine without `--input-file`. After that worked you saying the other command keeps failing and try to install the python extension?

One guess I could have is that maybe your python version output this command to stderr and it looks at stdout only but I don't get why it worked for the other command.

I think to go further we'd have to add debug logs to the code base in here https://github.com/Azure/autorest/blob/9eb229a8fc85e0c7d612cfd14791a1bda0ca14ed/packages/libs/extension/src/system-requirements/python.ts#L83-L104

**Comment by felixvd** [comment] 2021-11-24 02:52
Thanks for the quick response. It was `sudo` - root did not have python3 installed, the user did. That was a dumb error, so it's definitely on me. But maybe a more verbose print [here](https://github.com/Azure/autorest/blob/main/packages/libs/extension/src/system-requirements/version.ts#L35) might have given a hint.

**Comment by timotheeguerin** [comment] 2021-11-24 03:04
yeah that could be improved, do you know what the output is from running `sudo  python3 -c "import sys; print('.'.join(map(str, sys.version_info[:3])))"`

guessing some error gets logged to stderr and doesn't get propagated by autorest
