### ISSUE TITLE
[Java] The generated code does not support the none JSON type responses

### ISSUE THREAD

**Issue by pomortaz** [Azure/autorest#1312] opened 2016-07-27 00:23 UTC
If the return type is a none JSON string e.g. "abc" the Java generated code does not know how to serialize the response. In this case the AzureServiceResponseBuilder throws an error on the build(response) as follow:
com.fasterxml.jackson.core.**JsonParseException**: Unrecognized token 'abc': was expecting ('true', 'false' or 'null').

```
com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'xxx': was expecting ('true', 'false' or 'null')
 at [Source: xxx; line: 1, column: 112]
    at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1586)
    at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:521)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2754)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1820)
    at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:708)
    at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:3829)
    at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3774)
    at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2798)
    at com.microsoft.rest.serializer.JacksonMapperAdapter.deserialize(JacksonMapperAdapter.java:179)
    at com.microsoft.rest.ServiceResponseBuilder.buildBody(ServiceResponseBuilder.java:286)
    at com.microsoft.rest.ServiceResponseBuilder.build(ServiceResponseBuilder.java:142)
    at com.microsoft.azure.keyvault.implementation.KeyVaultClient.getPendingCertificateSigningRequestDelegate(KeyVaultClient.java:2016)
    at com.microsoft.azure.keyvault.implementation.KeyVaultClient.getPendingCertificateSigningRequest(KeyVaultClient.java:1967)
    at com.microsoft.azure.keyvault.test.CertificateOperationsTest.createCsr(CertificateOperationsTest.java:619)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
    at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
    at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)


```

**Comment by pomortaz** [comment] 2016-07-27 00:33
I think the solution is to use service response as follow, instead of the builder for none Json response cases e.g. byte[]:
```ServiceResponse<byte[]> serviceResponse = new ServiceResponse<byte[]>(response.body().bytes(), response);```

**Comment by martinsawicki** [comment] 2017-01-17 21:31
code gen issue?
workaround exists
in C# it seems to work ok.
pri-2

**Comment by fearthecowboy** [comment] 2017-07-17 21:58
@jianghaolu is this still an issue? can we close it?

**Comment by jianghaolu** [comment] 2017-07-17 22:55
Yes - it's by design. If a non-JSON response is intended, please use corresponding content types.

**Closed by jianghaolu** 2017-07-17 22:55 UTC
Labels: java
