### ISSUE TITLE
CI should verify that files are appropriately formatted (UTF-8, newlines, whitespace...)

### ISSUE THREAD

**Issue by kirthik** [Azure/autorest#1825] opened 2017-02-14 18:25 UTC
We need a linter rule for catching this one.

Moving from https://github.com/Azure/azure-rest-api-specs/issues/380 

cc @lvh

**Comment by veronicagg** [comment] 2017-04-21 18:04
is AutoRest doing this already? do we need to implement this in CI?

**Comment by dsgouda** [comment] 2017-04-21 18:10
Wonder if this should be linterized or should AutoRest automatically format the file before processing. @olydis thoughts?

**Comment by fearthecowboy** [comment] 2017-04-21 18:21
UTF-8 is all we produce.

We enforce `LF` line endings for certain extensions already, the rest are assumed to be `CRLF`. If there is one producing something not consistent with expectations, that can be updated.

G

**Comment by lvh** [comment] 2017-04-23 15:42
@fearthecowboy The original linked issue (#380) shows a counterexample: re UTF-8 and LF/CRLF endings.

@veronicagg  My suggestion for CI is mostly because the stuff you need to do to detect the problem is basically most of the work you need to do to get it in CI anyway, so I'd suggest doing it in CI to make sure that there are no regression instead of fixing it once :) The linked issue give some examples of commands you may want to run in CI; specifically, I'd suggest eclint and iconv.

I don't know what editor is popular among people who work on this but VS Code has a plugin for Editorconfig. https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig

**Comment by veronicagg** [comment] 2017-06-08 23:44
@vishrutshah is this something you think could be added to CI?

**Comment by vishrutshah** [comment] 2017-06-09 20:18
Based on the tool mentioned in the linked PR, Check is doable. I'd not prefer to correct those changes as part of the CI though. 

@kirthik This should be moved back to the azure-rest-api-spec repo instead of autorest. Let me know if you think otherwise then i can reopen the previous issue and close this one.

**Comment by fearthecowboy** [comment] 2017-07-18 17:43
reactivated in original repo

**Closed by fearthecowboy** 2017-07-18 17:43 UTC
