### ISSUE TITLE
Autorest change the input filepath and does not found it

### ISSUE THREAD

**Issue by lmazuel** [Azure/autorest#1778] opened 2017-02-02 02:06 UTC
This is something weird:
```console
mono AutoRest.exe -i /git-restapi/arm-datafactory/2015-10-01/swagger/service.json -o /tmp/tmpyx24_nun/service.json -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Namespace azure.mgmt.datafactory -PackageVersion 0.1.0 -ft 2
```

leads to:
```
FATAL: Error generating client model: System.Net.WebException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json". ---> System.Net.WebException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json". ---> System.IO.FileNotFoundException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0021a] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean useAsync) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.Net.FileWebStream..ctor (System.Net.FileWebRequest request, System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare sharing, System.Int32 length, System.Boolean async) [0x00000] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.FileWebStream:.ctor (System.Net.FileWebRequest,string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool)
  at System.Net.FileWebResponse..ctor (System.Net.FileWebRequest request, System.Uri uri, System.IO.FileAccess access, System.Boolean asyncHint) [0x0002c] in <59be416de143456b88b9988284f43350>:0
   --- End of inner exception stack trace ---
  at System.Net.FileWebResponse..ctor (System.Net.FileWebRequest request, System.Uri uri, System.IO.FileAccess access, System.Boolean asyncHint) [0x000af] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.FileWebResponse:.ctor (System.Net.FileWebRequest,System.Uri,System.IO.FileAccess,bool)
  at System.Net.FileWebRequest.GetResponseCallback (System.Object state) [0x00088] in <59be416de143456b88b9988284f43350>:0
   --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0008a] in <59be416de143456b88b9988284f43350>:0
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00027] in <59be416de143456b88b9988284f43350>:0
  at System.Net.WebClient.DownloadString (System.String address) [0x00019] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadString (string)
  at AutoRest.Core.Utilities.FileSystem.ReadFileAsText (System.String path) [0x00029] in <6d767340bc1f4e7e8792a78912a0b187>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x0010f] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x001d8] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x001b4] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson (System.String path, System.String swaggerDocument) [0x0001a] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Normalize (System.String path, System.String swaggerDocument) [0x00034] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Parse (System.String path, System.String swaggerDocument) [0x00000] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Load (System.String path, AutoRest.Core.Utilities.IFileSystem fileSystem) [0x00016] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerModeler.Build () [0x0004f] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Core.AutoRestController.Generate () [0x00073] in <6d767340bc1f4e7e8792a78912a0b187>:0
ERROR: Error generating client model: System.Net.WebException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json". ---> System.Net.WebException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json". ---> System.IO.FileNotFoundException: Could not find file "/git-restapi/arm-datafactory/2015-10-01/service.json".
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0021a] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.IO.FileOptions options) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean useAsync) [0x00000] in <dca3b561b8ad4f9fb10141d81b39ff45>:0
  at System.Net.FileWebStream..ctor (System.Net.FileWebRequest request, System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare sharing, System.Int32 length, System.Boolean async) [0x00000] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.FileWebStream:.ctor (System.Net.FileWebRequest,string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,bool)
  at System.Net.FileWebResponse..ctor (System.Net.FileWebRequest request, System.Uri uri, System.IO.FileAccess access, System.Boolean asyncHint) [0x0002c] in <59be416de143456b88b9988284f43350>:0
   --- End of inner exception stack trace ---
  at System.Net.FileWebResponse..ctor (System.Net.FileWebRequest request, System.Uri uri, System.IO.FileAccess access, System.Boolean asyncHint) [0x000af] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.FileWebResponse:.ctor (System.Net.FileWebRequest,System.Uri,System.IO.FileAccess,bool)
  at System.Net.FileWebRequest.GetResponseCallback (System.Object state) [0x00088] in <59be416de143456b88b9988284f43350>:0
   --- End of inner exception stack trace ---
  at System.Net.WebClient.DownloadDataInternal (System.Uri address, System.Net.WebRequest& request) [0x0008a] in <59be416de143456b88b9988284f43350>:0
  at System.Net.WebClient.DownloadString (System.Uri address) [0x00027] in <59be416de143456b88b9988284f43350>:0
  at System.Net.WebClient.DownloadString (System.String address) [0x00019] in <59be416de143456b88b9988284f43350>:0
  at (wrapper remoting-invoke-with-check) System.Net.WebClient:DownloadString (string)
  at AutoRest.Core.Utilities.FileSystem.ReadFileAsText (System.String path) [0x00029] in <6d767340bc1f4e7e8792a78912a0b187>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x0010f] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x001d8] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent (System.Collections.Generic.HashSet`1[T] visitedEntities, System.Collections.Generic.Dictionary`2[TKey,TValue] externalFiles, System.String currentFilePath, System.String entityType, System.String modelName, Newtonsoft.Json.Linq.JToken externalDoc) [0x001b4] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson (System.String path, System.String swaggerDocument) [0x0001a] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Normalize (System.String path, System.String swaggerDocument) [0x00034] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Parse (System.String path, System.String swaggerDocument) [0x00000] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerParser.Load (System.String path, AutoRest.Core.Utilities.IFileSystem fileSystem) [0x00016] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Swagger.SwaggerModeler.Build () [0x0004f] in <c0f21d1d16684152926e8aa58c112d50>:0
  at AutoRest.Core.AutoRestController.Generate () [0x00073] in <6d767340bc1f4e7e8792a78912a0b187>:0
```

You can see that `/git-restapi/arm-datafactory/2015-10-01/service.json` is not the filename I used as input. A parsing issue on Ubuntu?

This is from this file:
https://github.com/Azure/azure-rest-api-specs-pr/tree/master/arm-datafactory/2015-10-01/swagger

Autorest 20170131

@fearthecowboy ?

**Comment by lmazuel** [comment] 2017-02-02 17:13
Reproduced on Windows with build 20170201
```console
D:\> .\AutoRest.1.0.0-Nightly20170201\tools\AutoRest.exe -i ./arm-datafactory/2015-10-01/swagger/service.json -o /DataFactory -AddCredentials True -CodeGenerator Azure.Python -Header MI
CROSOFT_MIT_NO_VERSION -Namespace azure.mgmt.datafactory -PackageVersion 0.1.0 -ft 2
FATAL: Error generating client model: System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.IO.FileNotFoundException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AutoRest.Core.Utilities.FileSystem.ReadFileAsText(String path)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Normalize(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Parse(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.IO.FileNotFoundException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AutoRest.Core.Utilities.FileSystem.ReadFileAsText(String path)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Normalize(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Parse(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
ERROR: AutoRest.exe -i ./arm-datafactory/2015-10-01/swagger/service.json -o /DataFactory -AddCredentials True -CodeGenerator Azure.Python -Header MICROSOFT_MIT_NO_VERSION -Namespace azure.mgmt.datafactory -PackageVersion 0.1.0 -ft 2
```

**Comment by fearthecowboy** [comment] 2017-02-02 17:24
WHAT THE!?

@olydis can you look into this?

**Comment by lmazuel** [comment] 2017-02-02 17:48
@fearthecowboy @olydis If it helps, it's working on AutoRest.0.17.3 (according to the ADF team)

**Comment by fearthecowboy** [comment] 2017-02-02 17:49
It's likely because of some file-path-resolution stuff that went in the in last couple months.

**Comment by lmazuel** [comment] 2017-02-02 18:01
@olydis @fearthecowboy I've done a manual "git bisect" like test and this is failing in Autorest 20161214 (it's working in 13, broke in 14).

**Comment by olydis** [comment] 2017-02-09 01:22
Indeed, external reference resolving has a bug. The problem is not with loading the file you stated on the command line (that one is actually found and loaded), but with resolving references recursively: `service.json` references a file `folder/asd.json` that (correctly) references back to `service.json` by saying `../service.json`. Apparently AutoRest tries to resolve that relative to the ORIGINAL file instead of relative to `folder/asd.json`. This also blew up CI for https://github.com/Azure/azure-rest-api-specs/pull/913, a fix is on its way!

**Comment by olydis** [comment] 2017-02-10 01:34
fixed by #1805

**Comment by lmazuel** [comment] 2017-02-13 18:10
@olydis @fearthecowboy still broken in Autorest 20170212
```console
FATAL: Error generating client model: System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.IO.FileNotFoundException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AutoRest.Core.Utilities.FileSystem.ReadFileAsText(String path)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Normalize(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Parse(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.Net.WebException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'. ---> System.IO.FileNotFoundException: Could not find file 'D:\arm-datafactory\2015-10-01\service.json'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
   at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   --- End of inner exception stack trace ---
   at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
   at System.Net.FileWebRequest.GetResponseCallback(Object state)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at AutoRest.Core.Utilities.FileSystem.ReadFileAsText(String path)
   at AutoRest.Swagger.SwaggerParser.EnsureCompleteDefinitionIsPresent(HashSet`1 visitedEntities, Dictionary`2 externalFiles, String currentFilePath, String entityType, String modelName, JToken externalDoc)
   at AutoRest.Swagger.SwaggerParser.ResolveExternalReferencesInJson(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Normalize(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerParser.Parse(String path, String swaggerDocument)
   at AutoRest.Swagger.SwaggerModeler.Build()
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
```

**Comment by lmazuel** [comment] 2017-02-13 19:01
Actually it's worse, I got a workaround before (thanks @annatisch) by copy/pasting the files in at several level (so this was always found....). But with this version I now get:
```console
FATAL: Error generating client model: System.ArgumentException: Reference path 'LinkedService' does not exist in the definition section of the Swagger document.
   at AutoRest.Swagger.SchemaResolver.DereferenceInner(String referencePath, List`1 visitedReferences)
   at AutoRest.Swagger.SchemaResolver.Unwrap(Schema schema)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.ObjectBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SwaggerModeler.BuildCompositeTypes()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Error generating client model: System.ArgumentException: Reference path 'LinkedService' does not exist in the definition section of the Swagger document.
   at AutoRest.Swagger.SchemaResolver.DereferenceInner(String referencePath, List`1 visitedReferences)
   at AutoRest.Swagger.SchemaResolver.Unwrap(Schema schema)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.ObjectBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SchemaBuilder.BuildServiceType(String serviceTypeName)
   at AutoRest.Swagger.SwaggerModeler.BuildCompositeTypes()
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at AutoRest.Core.AutoRestController.Generate()
ERROR: Code generation failed.
```

**Comment by amarzavery** [comment] 2017-02-13 19:24
Looking at it.

**Comment by olydis** [comment] 2017-03-08 19:42
@lmazuel think this got fixed -- shout if not! :)

**Closed by olydis** 2017-03-08 19:42 UTC
Labels: bug
