### ISSUE TITLE
Error: '$.definitions.xxx' has incompatible values 

### ISSUE THREAD

**Issue by SudhindraKovalam** [Azure/autorest#3407] opened 2020-02-08 19:13 UTC
ran the following command on my branch
`npx autorest --reset && npx autorest --validation --azure-validator --message-format=json specification/maps/data-plane/readme.md`

results in a failure, the issue reported is:
```
  '    at Object.MergeYamls (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:221:23)\n' +
  '    at Object.ComposeSwaggers (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/swagger-loader.js:380:36)\n' +
  '    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n' +
  '    at async /home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/pipeline.js:100:25\n' +
  '    at async ScheduleNode (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/pipeline.js:322:33)\n' +
  '(node:5619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 104)\n' +
  "(node:5619) UnhandledPromiseRejectionWarning: Error: '$.definitions.MapTileResult.description' has incompatible values (---\n" +
  'This image is returned from a successful Map Tile call\n' +
  ', ---\n' +
  'The tile returned from a successful API call.\n' +
  ').\n' +
  '    at Merge (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:58:11)\n' +
  '    at Merge (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:53:31)\n' +
  '    at Merge (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:53:31)\n' +
  '    at Merge (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:53:31)\n' +
  '    at Object.MergeYamls (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/source-map/merging.js:221:23)\n' +
  '    at Object.ComposeSwaggers (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/swagger-loader.js:380:36)\n' +
  '    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n' +
  '    at async /home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/pipeline.js:100:25\n' +
  '    at async ScheduleNode (/home/vsts/.autorest/@microsoft.azure_autorest-core@2.0.4413/node_modules/@microsoft.azure/autorest-core/dist/lib/pipeline/pipeline.js:322:33)\n' +
  '(node:5619) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 105)\n' +
  "  Error: '$.definitions.MapTileResult.description' has incompatible values (---\n" +
  'This image is returned from a successful Map Tile call\n' +
  ', ---\n' +
  'The tile returned from a successful API call.\n' +
  ').]'
```
Here is the [link](https://dev.azure.com/azure-sdk/public/_build/results?buildId=256002&view=results) to the build.
Looking into the error a bit, it looks like auto rest is complaining that the `$.definitions.MapTileResult.description` has incompatible value and the reason it seems to complain, The `MapTileResult` object has changed between two versions of our API. 
- in `v1` it was an object 
```json
"MapTileResult": {
      "description": "This image is returned from a successful Map Tile call",
      "type": "object",
      "format": "file",
      "readOnly": true
    }
```
- in `v2` its a binary string
```json
"MapTileResult": {
      "description": "The tile returned from a successful API call.",
      "type": "string",
      "format": "binary",
      "readOnly": true
    }
```
This is blocking us from merging our data-plane rest API specs into the master branch. Please help

**Comment by SudhindraKovalam** [comment] 2020-02-08 19:16
This issue blocks [this pr](https://github.com/Azure/azure-rest-api-specs/pull/8338)

**Comment by fearthecowboy** [comment] 2020-02-10 22:55
No. You have two copies of the same model and they are not identical.

your configuration has a section:

~~~ markdown
``` yaml $(tag) == 'package-1.0'
input-file: 
  - ./Data/preview/v1/data.json
  - ./Geolocation/preview/v1/geolocation.json
  - ./Mobility/preview/v1/mobility.json
  - ./Render/preview/v1/render.json  # YOU CAN'T MERGE BOTH VERSIONS
  - ./Render/preview/v2/render.json  # OF THIS API TOGETHER in AutoRest V2.
  - ./Route/preview/v1/route.json
  - ./Search/preview/v1/search.json
  - ./Spatial/preview/v1/spatial.json
  - ./TimeZone/preview/v1/timezone.json
  - ./Traffic/preview/v1/traffic.json
  - ./Weather/preview/v1/weather.json
```
~~~

You can't have both versions of the API in the same package in AutoRest  v2. You're literally trying to merge them together.

Remove one of them from the configuration and try again.

closing -- not a bug.

**Closed by fearthecowboy** 2020-02-10 22:55 UTC
