### ISSUE TITLE
Serviceclient generating wrong code (Java)

### ISSUE THREAD

**Issue by asebak** [Azure/autorest#889] opened 2016-03-27 19:20 UTC
In this file https://github.com/Azure/autorest/blob/master/AutoRest/Generators/Java/Java/Templates/ServiceClientTemplate.cshtml#L134
This has two code errors, unless I am missing some specific dependencies in maven, which I doubt:

`    
protected void initialize() {
        if (this.credentials != null)
        {
            this.credentials.applyCredentialsFilter(this.client);
        }
        super.initialize();
        this.retrofitBuilder.baseUrl(baseUrl);
    }
`

this.client does not exist, it should be this.clientBuilder.  Also  this.retrofitBuilder.baseUrl(baseUrl); does not accept a AutoRestBaseUrl baseUrl.  It should be a string or HttpUrl.

**Comment by devigned** [comment] 2016-03-27 19:53
Thank you. It's assigned and we'll investigate.

**Comment by jianghaolu** [comment] 2016-03-28 05:12
Thanks @asebak! These are valid bugs.

**Comment by jianghaolu** [comment] 2016-03-28 21:19
@asebak 

The 1st issue is going to be resolved in an upcoming pull request.

The 2nd one is not an issue. `AutoRestBaseUrl` derives from `okhttp3.HttpUrl.BaseUrl` which actually allows modifying the url any time by design.

**Closed** 2016-03-29 00:46 UTC
Labels: java
