### ISSUE TITLE
ListByOperationsValidation: split rule

### ISSUE THREAD

**Issue by veronicagg** [Azure/autorest#1929] opened 2017-03-07 00:11 UTC
Let's split the rule in 4 rules, each list, plus, if operation group does not match the resource type in the path. Operation group not matching, should be a warning, rest should be Errors.

**Comment by sarangan12** [comment] 2017-03-24 21:54
This is duplicate of https://github.com/Azure/autorest/issues/1861. Closing this one

**Closed by sarangan12** 2017-03-24 21:54 UTC
Labels: bug, linter
