### ISSUE TITLE
System.Collections.Generic.KeyNotFoundException: Please specify a field with type of System.Byte[] to deserialize the file contents to

### ISSUE THREAD

**Issue by Danielmdmu** [Azure/autorest#2460] opened 2017-07-19 07:50 UTC
If I try to run Autorest against our SwaggerAPI or the resulting JSON I get this Error-Message.
It doesn't matter which Codgenerator I choose, in example here NodeJS.
I have no idea whats the Problem. 
Is there a Problem with the JSON-File or Autorest Failure?

Debug-Information:
```
autorest --input-file="D:\Test\test2.json" --output-folder="D:\Test\autorest" --nodejs --debug
[9:27:25] Network Enabled: true
AutoRest Code Generator
(c) 2017 Microsoft Corporation. https://aka.ms/autorest
DEBUG: Creating ConfigurationView : 4 sections.
DEBUG: Creating ConfigurationView : 21 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: pipeline-emitter - START
DEBUG: swagger-document-override/md-override-loader - START
DEBUG: swagger-document/loader - START
DEBUG: Emitting 'pipeline' at file:///D:/Test/autorest/pipeline
DEBUG: pipeline-emitter - END
DEBUG: swagger-document-override/md-override-loader - END
DEBUG: swagger-document/loader - END
DEBUG: swagger-document/individual/transform - START
DEBUG: swagger-document/individual/transform - END
DEBUG: swagger-document/compose - START
DEBUG: swagger-document/compose - END
DEBUG: swagger-document/transform-immediate - START
DEBUG: Creating ConfigurationView : 2 sections.
DEBUG: swagger-document/transform-immediate - END
DEBUG: swagger-document/transform - START
DEBUG: swagger-document/transform - END
DEBUG: swagger-document/emitter - START
DEBUG: nodejs/modeler - START
DEBUG: Emitting 'swagger-document' at file:///D:/Test/autorest/test2
DEBUG: swagger-document/emitter - END
FATAL: System.Collections.Generic.KeyNotFoundException: Please specify a field with type of System.Byte[] to deserialize the file contents to
   at AutoRest.Swagger.OperationBuilder.VerifyFirstPropertyIsByteArray(CompositeType serviceType)
   at AutoRest.Swagger.OperationBuilder.TryBuildStreamResponse(HttpStatusCode responseStatusCode, OperationResponse response, Method method, List`1 types, IModelType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildResponses(Method method, CompositeType headerType)
   at AutoRest.Swagger.OperationBuilder.BuildMethod(HttpMethod httpMethod, String url, String methodName, String methodGroup)
   at AutoRest.Swagger.SwaggerModeler.Build(ServiceDefinition serviceDefinition)
   at Modeler.<ProcessInternal>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NewPlugin.<Process>d__11.MoveNext()
FATAL: nodejs/modeler - FAILED
FATAL: Error: Plugin modeler reported failure.
Process() Cancelled due to exception : Plugin modeler reported failure.
Error: Plugin modeler reported failure.
    at C:\Users\muelldan\.autorest\plugins\autorest\1.2.0\node_modules\autorest-core\lib\pipeline\pipeline.js:90:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\muelldan\AppData\Roaming\npm\node_modules\autorest\lib\polyfill.min.js:14:62)
    at <anonymous>
```

Regards
Daniel

**Comment by fearthecowboy** [comment] 2017-07-19 15:03
It's something to do with the swagger.

See the ` Please specify a field with type of System.Byte[] to deserialize the file contents to`

If you posted it here, I could take a look.

**Comment by fearthecowboy** [comment] 2017-07-19 16:36
I think it's a bit of both. 

I suspect this is something wrong in AutoRest, but it's being triggered by something else in the file.

**Comment by fearthecowboy** [comment] 2017-07-19 16:52
Look for a method that has a `produces ` that's not `application/json` .

(this is a terrible failing in AutoRest, but the issue is that it's trying to create a method with a stream parameter when it doesn't think it's a `application/json` )

G

**Comment by dsgouda** [comment] 2017-09-26 21:53
@Danielmdmu are you still facing issues here? Please point me to the Swagger spec and I can take a look

**Comment by Danielmdmu** [comment] 2017-09-27 07:34
@dsgouda currently I'm not working on this topic. 
I've planned to research this issue with one of my co-workers who's responsible for our REST-Interface

**Comment by tientq** [comment] 2017-09-29 09:19
I have same issue.

**Comment by fearthecowboy** [comment] 2017-09-29 15:13
@tientq

Your cause is the same as the previous one:


> Look for a method that has a `produces` that's not **application/json** .

> (this is a terrible failing in AutoRest, but the issue is that it's trying to create a method with a stream parameter when it doesn't think it's a application/json )

change your `produces` to `application/json` -- describing your api as "I can return any content type in the universe" probably isn't correct.

**Comment by MiYanni** [comment] 2019-11-07 00:51
Fix provided. Closing.

**Closed by MiYanni** 2019-11-07 00:51 UTC
