### ISSUE TITLE
AzureEnvironment

### ISSUE THREAD

**Issue by orkeret** [Azure/autorest#2235] opened 2017-05-03 11:14 UTC
Hi,
I'm referring to this class:
autorest-clientruntime-for-java/azure-client-runtime/src/main/java/com/microsoft/azure/AzureEnvironment.java

The managementEndpoint up until a couple of months ago was terminating with a "/", the behavior has been recently changed and now this slash has been omitted (known impacts are for the REST API authentication bit which expecting a resource URI with a terminating slash - POST /{tenantId}/oauth2/token).

You can find the commit that caused that behavioral change [here](https://github.com/Azure/autorest-clientruntime-for-java/commit/655c07b88a395ed264c868b9c73f17c8cbb319b6)

Please note that there is also some inconsistencies which might cause other issues with the resourceManagerEndpointUrl (in the "default" azure environment it terminates with a slash while the other environments aren't terminating with a slash)

Cheers,
Or

**Comment by jianghaolu** [comment] 2017-05-03 17:15
Closing as this is a duplicate of https://github.com/Azure/azure-sdk-for-java/issues/1638.

**Closed by jianghaolu** 2017-05-03 17:15 UTC
Labels: java
