### ISSUE TITLE
x-ms-client-name not honored for query parameter 

### ISSUE THREAD

**Issue by joheredi** [Azure/autorest#3681] opened 2020-01-31 19:09 UTC
**Describe the issue**
I'm trying to rename a parameter with a transform in readme.md, however I'm not able to rename some parameters. For example working with this [swagger](https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json), this transform doesn't seem to work:

```yaml
directive:
  - from: swagger-document
    where: $.paths..parameters[*]
    transform: >
      if ($.name === "showStats") {
        $["x-ms-client-name"] = "includeStatistics";
      }
```
However if I target a different parameter it works

```yaml
directive:
  - from: swagger-document
    where: $.paths..parameters[*]
    transform: >
      if ($.name === "input") {
        $["x-ms-client-name"] = "fooBar";
      }

```

It seems to be ignoring `x-ms-client-name` on query parameters, while body parameters honor it.

I ran autorest with `--interactive` and in the file just before the first codemodel file, I can see that the parameter has the `x-ms-client-name` property added in the transform
![image](https://user-images.githubusercontent.com/21109913/73566774-88e80680-4419-11ea-82e8-7b8355ecba96.png)

** REQUIRED ** 
**ModelerFour** version: 4.4.158
**AutoRest-core** version: 3.0.6192
**CommandLine** : autorest --typescript --use=<LOCAL_AUTOREST.TYPESCRIPT_REPO>
OpenAPI/Swagger file: https://raw.githubusercontent.com/Azure/azure-rest-api-specs/master/specification/cognitiveservices/data-plane/TextAnalytics/preview/v3.0-preview.1/TextAnalytics.json

**Comment by timotheeguerin** [comment] 2021-01-05 16:39
Hey @joherdi, this seems to be fixed now, for this openapi3
```json
 "paths": {
    "/test": {
      "get": {
        "operationId": "test",
        "parameters": [
          {
            "name": "foo",
            "x-ms-client-name": "fooBar",
            "in": "query",
            "description": "Foo bar",
            "schema": { "type": "string" }
          }
        ],
...
```
![image](https://user-images.githubusercontent.com/1031227/103672372-12a92980-4f31-11eb-8742-d9f3fb7ebc7a.png)
The typescript code also include the right name 
![image](https://user-images.githubusercontent.com/1031227/103672555-4be19980-4f31-11eb-881d-94b1b9c82cc6.png)

If you can still reproduce the issue, please reopen and  can you share the openapi file

**Closed by timotheeguerin** 2021-01-05 16:39 UTC
Labels: Modeler
