### ISSUE TITLE
AutoRest should provide a way to disable client-side validation

### ISSUE THREAD

**Issue by brjohnstmsft** [Azure/autorest#2100] opened 2017-03-31 23:19 UTC
A frequent piece of feedback I get when changing a Swagger spec is that I'm not documenting min/max length and regex rules for certain string properties such as resource names. I should do this for documentation purposes, but I don't.

The reason I don't include regex constraints and the like is because AutoRest uses them to generate client-side validation code, which I don't want. It introduces too much coupling between the client and the service and makes versioning more painful for practically zero benefit. I expand more on this line of reasoning in the [discussion in this PR](https://github.com/Azure/azure-rest-api-specs/pull/637).

Client-side validation can make sense in the context of a UI where round-trip time is important and you need to preserve the user's work, but in the context of a library that directly calls a REST API it makes little sense.

**Comment by tailo** [comment] 2017-04-04 22:47
We use auto generated sdk's for integration testing, the client side validation prevents us from writing a lot negative test cases.

**Comment by olydis** [comment] 2017-05-03 16:10
@brjohnstmsft @tailo A configuration point to disable client side validation in C# should be in the latest nightly, see https://github.com/olydis/autorest/blob/master/Samples/1d-common-settings/readme.md (specifically `client-side-validation: false`) for an example. As we will move away from the legacy CLI, I haven't tested the switch there, but if I'm not mistaken it should be usable as `-ClientSideValidation false`.

Let me know if you have any questions, whether I have missed tying some validation to that flag or if something doesn't work! 🙂

**Comment by olydis** [comment] 2017-05-03 16:11
reopening to tag the languages I haven't touched (not even sure if they have client side validation in the first place)

**Comment by olydis** [comment] 2017-07-18 17:50
To the language owners I've tagged: Please check whether your language supports client side validation.
If so, please imitate C#'s behavior of respecting the flag mentioned above (`Settings.Instance.Host.GetValue<bool?>("client-side-validation")` should get you the setting wherever you need it). If not, I assume that your customers never requested client side validation in the first place and you're off the hook.

Note that allowing to disable validation was done in C# due to strong customer feedback and the fact that it actually contradicts the Swagger spec (that says that constraints are enforced by the server side). By default, AutoRest core sets this setting to true to maintain backwards compatibility.

**Comment by mcardosos** [comment] 2017-09-01 20:13
Now supported on Go

**Comment by lmazuel** [comment] 2017-09-28 18:20
@olydis @fearthecowboy duplicate of https://github.com/Azure/autorest/issues/1583?

**Comment by olydis** [comment] 2017-09-28 18:28
lol, indeed, closed the other one since there seems to be more traction on this issue here :D

**Comment by lmazuel** [comment] 2017-10-03 17:09
[Will be released in autorest.python 2.0.15](https://github.com/Azure/autorest.python/pull/11). [Needs msrest >= 0.4.15 to work](https://github.com/Azure/msrest-for-python#2017-09-28-version-0415) (will be just ignored if < 0.4.15, will not crash).

**Comment by sarangan12** [comment] 2017-11-10 07:21
With PRs https://github.com/Azure/azure-sdk-for-ruby/pull/1119 and https://github.com/Azure/autorest.ruby/pull/16 Ruby has added conditions that validations will not happen if the client side validation is set to false. Let me know if there is anything else to do on our side

**Comment by sarangan12** [comment] 2017-11-10 07:22
Also changing the node assignment from @balajikris to @amarzavery

**Comment by shaunnez** [comment] 2018-08-12 22:34
Any update when this will be done for the typescript version?

**Comment by lmazuel** [comment] 2018-08-13 17:26
@RikkiGibson for TS

**Comment by RikkiGibson** [comment] 2018-08-13 18:02
tracking in Azure/autorest.typescript#243

**Comment by shabfactor** [comment] 2018-08-15 01:04
@RikkiGibson  any eta for TS?

**Closed** 2019-11-22 21:46 UTC
Labels: enhancement, java, nodejs, typescript
