### ISSUE TITLE
C# code fails if it recieves a service unavailible response on Linux

### ISSUE THREAD

**Issue by csteegz** [Azure/autorest#1564] opened 2016-11-02 21:43 UTC
C# generated code fails during a retry on Linux if the service receives a 503. 

This is in Centos 7.1.1503 using dotnet core 1.01 and version 2.3.3 of Rest.ClientRuntime package

```
Unhandled Exception: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.__Error.StreamIsClosed()
   at System.IO.MemoryStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.MemoryStream.ReadAsync(Byte[] buffer, Int32 offset, Int32 count, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Net.Http.CurlHandler.MultiAgent.TransferDataFromRequestStream(IntPtr buffer, Int32 length, EasyRequest easy)
   at System.Net.Http.CurlHandler.MultiAgent.CurlSendCallback(IntPtr buffer, UInt64 size, UInt64 nitems, IntPtr context)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at flaky.Echo.<FlakyPostWithHttpMessagesAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at flaky.EchoExtensions.<FlakyPostAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at flaky.EchoExtensions.FlakyPost(IEcho operations, Request request)
   at POC.Program.Main(String[] args)
```

This does not happen on Windows. 
It appears that the request object is being disposed before the RetryDelegatingHandler is able to copy it into another request. I think this might be at it's root an HTTPClient error, but I think the RetryDelegatingHandler is needed to repro.

I've attached a minimal POC with a python server, the swagger and the generated code. 

[AutorestBugPoC.zip](https://github.com/Azure/autorest/files/567743/AutorestBugPoC.zip)

**Comment by fearthecowboy** [comment] 2016-11-02 23:11
If the problem is what I think it is, this may be a bug we found in the dotnet runtime 1.0.0 -- I beleive the bug is fixed in newer builds but I didn't have the opportunity to find out which one. 

@markiiantsymbalista ran into this too, and indicated that he solved it with an update (see #1537 )

**Comment by csteegz** [comment] 2016-11-03 01:00
We're using 1.0.1, which is the latest supported release. I guess it's fixed in the 1.1 preview?

**Comment by fearthecowboy** [comment] 2016-11-03 15:25
I can only guess -- @markiiantsymbalista  ? Can you fill us in on what you did?

I'm stuck fixing some build issues this morning; after that I'll see if I can put up an environment to replicate this and track down where the fixes are.

**Comment by markiiantsymbalista** [comment] 2016-11-08 17:13
.net core migrated from dnx to .net cli. I just changed app and every class library to use it

From 

  "frameworks": {
    "netstandard1.6": {
      "imports": "dnxcore50"
    }
  },


to 

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }

**Comment by fearthecowboy** [comment] 2017-07-17 20:53
IIRC, this is corrected. If this is still an issue, please reopen with details.

**Closed by fearthecowboy** 2017-07-17 20:53 UTC
