### ISSUE TITLE
Go generator not always generating "enums"

### ISSUE THREAD

**Issue by mcardosos** [Azure/autorest#1667] opened 2016-12-07 22:24 UTC
For [example](https://github.com/Azure/azure-sdk-for-go/issues/483)

**Comment by mcardosos** [comment] 2016-12-08 23:42
Could you verify how this should work?

**Comment by jhendrixMSFT** [comment] 2016-12-16 18:55
I believe this is by design as this enum type is modeled as a string type.  I see the same pattern for other SDKs.  Please reopen if you disagree.

**Comment by mcardosos** [comment] 2016-12-30 21:15
Just like the [SkuName](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L248) enum is generated like this...
```go
// SkuName enumerates the values for sku name.
type SkuName string

const (
	// Premium specifies the premium state for sku name.
	Premium SkuName = "premium"
	// Standard specifies the standard state for sku name.
	Standard SkuName = "standard"
)
```
... [SkuFamily](https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L239) should be generated like this...
```go
// SkuFamily enumarates the values for sku family.
type SkuFamily string

const (
	// A specifies the A state fo sku family
	A SkuFamily = "A"
)
```
I don't think it has to do with being modeled as as string type, because SkuName is modeled like that too.

**Comment by mcardosos** [comment] 2016-12-30 21:37
This would change other structs. For example, Sku would look like this...
```go
// Sku is sKU details
type Sku struct {
	Family SkuFamily `json:"family,omitempty"`
	Name   SkuName   `json:"name,omitempty"`
}
```
... instead of like this...
```go
// Sku is sKU details
type Sku struct {
	Family *string `json:"family,omitempty"`
	Name   SkuName   `json:"name,omitempty"`
}
```
Validation code inside functions would also be modified.

**Comment by jhendrixMSFT** [comment] 2017-01-04 19:18
@mcardosos I'm still investigating however note that SkuName is not modeled as a string, see https://github.com/Azure/azure-rest-api-specs/blob/master/arm-keyvault/2015-06-01/swagger/keyvault.json#L254.

**Comment by mcardosos** [comment] 2017-01-04 19:24
:I maybe the true culprit is the swagger?

**Comment by jhendrixMSFT** [comment] 2017-01-04 19:28
It's possible.
@amarzavery Can you help us understand why SkuFamily is modeled as a string?  What's the general rule when deciding to model an enum as a string or not?

**Comment by jhendrixMSFT** [comment] 2017-01-20 21:34
Ping @amarzavery

**Comment by jhendrixMSFT** [comment] 2017-03-06 18:25
I did some more digging, the current implementation in AutoRest will treat this enum as a constant because it contains only one value, therefore it will not generate it as an enum type but as its underlying type.  The offending code is here.
https://github.com/Azure/autorest/blob/master/src/modeler/AutoRest.Swagger/ObjectBuilder.cs#L56
@olydis presumably this is by design, do you have insight as to why?  It seems a bit dodgy, e.g. if more values are added to the enum in the future then it will be modeled as a proper enum which would introduce a breaking change in SDKs with strongly-typed languages.

**Comment by olydis** [comment] 2017-03-06 20:07
I was told this was indeed implemented on purpose to support constants - I think there is consensus among us (the current devs) that this was a horrible decision (why not "x-ms-constant" or something!?) but I think we already have people relying on this behavior now!
Not sure, maybe the behavior is different if you play around with model-as-string and such?

**Comment by jhendrixMSFT** [comment] 2017-03-06 20:26
I see, thanks for the explanation (and for the record I agree that this behavior is unfavorable).  Since this is working as designed I'm going to close this issue.

**Closed by jhendrixMSFT** 2017-03-06 20:26 UTC
Labels: go, P1
