### ISSUE TITLE
No error received from server

### ISSUE THREAD

**Issue by bernardvoss** [Azure/autorest#584] opened 2016-01-05 12:57 UTC
We've generated a new client using our swagger input. All the calls work fine. The problem starts whenever our server throws an error for whatever reason. In that case the client just hangs and nothing happens.  This only happens in our C# clients.  The only thing that we have found is that by lowering the time out value we can get a Task Cancelled exception and then just show a generic message that a problem has occured. 

The same problem does not occur within our javascript clients. 

Any suggestions how to solve this problem ? We really like the client that are generated but if error handling cannot work properly we need to switch back to manual client building which will cost us a shit load of time .

**Comment by devigned** [comment] 2016-01-05 17:31
@bernardvoss any chance you can run this through fiddler, charles or some other debugging proxy? Either that, or provide a sample that repros this behavior.

Also, please provide some environmental details (Linux / Windows, .Net Core / Desktop, etc...).

There must be a bug there, but based on this report it's tough to determine a root cause.

**Comment by bernardvoss** [comment] 2016-01-06 13:36
OK some more details:
Environement: Visual Studio 2015 Update 1, Windows 10 Enterprise, Normal .Net 4.6  Framework. 
The following references excist in the project
IdentityModel 
Microsoft.Rest.ClientRun
Newtonsoft.Json,
System.Net.Http

After some more research I've found the following: Whenever I Disable diagnostics tools everything works as expected.

**Comment by stankovski** [comment] 2016-01-22 18:35
Fixed in https://github.com/Azure/autorest/pull/625

**Closed by stankovski** 2016-01-22 18:35 UTC
