### ISSUE TITLE
AutoRest not generating empty classes/models

### ISSUE THREAD

**Issue by grofit** [Azure/autorest#2549] opened 2017-08-23 08:57 UTC
I assume this is intended behaviour but we have an API (using Swashbuckle) which has an empty class which is used as a response type as at some point it will have data, but just not in this sprint.

```
// This is what I mean
public class SomeResponseObject {}

public class SomeController : ApiController
{
   [SwaggerResponse("SomeResponseObject", typeof(SomeResponseObject)]
   public IHttpResult DoSomething() { return Ok(new SomeResponseObject()); }
}
```
So in this scenario we can view the swagger ui and it seems to be outputting the right information, however when we go to generate the client for this in another project via autorest the generated API does not contain a `SomeResponseObject` class, and instead of expecting `DoSomething` to return a `SomeResponseObject` it returns an `object`, which I kind of understand as its just an empty object so it makes no real difference in most situations.

However in the scenario here, there is a form of facade API which re-wraps a call and passes it out, however the wrapped call returns back the same type, but it cannot access that type as its not there, and blows up and wont compile, however I don't feel that setting the response to be an object in the facade layer is the solution here. As at some point that object had properties, and in the next couple of sprints it will probably have properties again, but at this interim point it seems that autorest is trying to 2nd guess the intent here.

So is this expected behaviour? and if so is there a way to enforce it generating empty classes?

**Comment by olydis** [comment] 2017-09-07 03:14
can you provide the Swagger that causes this issue? Note that we have no control over Swashbuckle, but maybe we can do something to make AutoRest generate the type you expect - looking at the Swagger we can see what the problem is.

If Swashbuckle is not putting the expected type into the generated Swagger, there's not much we can do. On the other hand, if there's an empty type in the Swagger that AutoRest doesn't generate code for, we'll gladly address the problem and use (a reduced version of) your Swagger as a test case 🙂

**Comment by grofit** [comment] 2017-09-07 08:32
Hey thanks for getting back to me, here is what is generated from swashbuckle:

```json
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Test.API"
  },
  "host": "localhost",
  "schemes": [
    "http"
  ],
  "paths": {
    "/test/emptyobject": {
      "get": {
        "tags": [
          "Test"
        ],
        "operationId": "Test_EmptyObject",
        "consumes": [
          
        ],
        "produces": [
          "application/json",
          "text/json",
          "application/xml",
          "text/xml"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "$ref": "#/definitions/Test.API.Controllers.Api.EmptyClass"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "Test.API.Controllers.Api.EmptyClass": {
      "type": "object",
      "properties": {
        
      }
    }
  }
}
```

Everything seems to set `type` to be `object` even on models with properties, but as you can see it adds the output class but there is just no properties provided (as it is currently an empty class).

**Comment by olydis** [comment] 2017-09-07 16:50
This will be fixed with the next AutoRest release (next week). You will have to specify `--generate-empty-classes` on the command line since we want to remain backwards compatible with stuff that was generated in the past (including the quirks...)

**Closed** 2017-09-27 19:37 UTC
