### ISSUE TITLE
Autorest does not start code generation

### ISSUE THREAD

**Issue by kant2002** [Azure/autorest#3560] opened 2020-08-05 09:57 UTC
When invoking autorest in folder with working literate MD file nothing generated. When switch to Node 12 or 
```
autorest --latest

WARNING: AutoRest has not been tested with Node versions greater than v13.

AutoRest code generation utility [cli version: 3.0.6187; node: v14.4.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\xxxx\.autorest\@autorest_core@3.0.6306\node_modules\@autorest\core\dist' (3.0.6306)
[3.47 s] Generation Complete
```

when run ` autorest --version=3.0.5537`
everything become normal

```
autorest --version=3.0.5537

WARNING: AutoRest has not been tested with Node versions greater than v13.

AutoRest code generation utility [cli version: 3.0.6187; node: v14.4.0, max-memory: 8192 gb]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\xxxx\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5537)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.683)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
INFORMATION: The output folder doesn't contain a pre-existing package.json file to get the package version from.
[35.04 s] Generation Complete
```

**Comment by daviwil** [comment] 2020-10-08 22:58
@kant2002 If you run `autorest --reset` and try this again, does it resolve the issue?  We've released a few updates since then, maybe one of them has resolved this issue.

**Comment by kant2002** [comment] 2020-12-21 12:48
@daviwil No it did not. I test each of new version and on some APIs this plainly does not work. Up to 3.0.6322
Only `autorest --version=3.0.5537` do the trick.
What steps can I take to troubleshoot the issue?

```
> autorest --debug

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.2.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\user\.autorest\@autorest_core@3.0.6320
   Loading AutoRest core      'C:\Users\user\.autorest\@autorest_core@3.0.6320\node_modules\@autorest\core\dist' (3.0.6320)
DEBUG [3.5 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [3.5 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [3.5 s]: pipeline-emitter - START inputs = 0
DEBUG [3.52 s]: configuration-emitter - START inputs = 0
DEBUG [3.53 s]: pipeline-emitter - END [0.03 s]
DEBUG [3.53 s]: configuration-emitter - END [0.03 s]
DEBUG [3.86 s]: swagger-document/loader-swagger - END [0.36 s]
DEBUG [3.86 s]: swagger-document/individual/transform - SKIPPING
DEBUG [3.86 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [3.86 s]: swagger-document/identity - SKIPPING
DEBUG [3.86 s]: swagger-document/individual/identity - SKIPPING
DEBUG [3.88 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [4.24 s]: openapi-document/loader-openapi - END [0.73 s]
DEBUG [4.24 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [4.3 s]: openapi-document/individual/transform - END [0.06 s]
DEBUG [4.3 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [4.51 s]: openapi-document/individual/schema-validator-openapi - END [0.2 s]
DEBUG [4.51 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [4.51 s]: openapi-document/individual/identity - END [0 s]
DEBUG [4.51 s]: openapi-document/transform - START inputs = 1
DEBUG [4.57 s]: openapi-document/transform - END [0.05 s]
DEBUG [4.57 s]: openapi-document/allof-cleaner - START inputs = 1
DEBUG [4.59 s]: openapi-document/allof-cleaner - END [0.02 s]
DEBUG [4.59 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [5.15 s]: openapi-document/tree-shaker - END [0.56 s]
DEBUG [5.16 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [6.24 s]: openapi-document/multi-api-merger - END [1.08 s]
DEBUG [6.24 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [6.95 s]: openapi-document/components-cleaner - END [0.71 s]
DEBUG [6.95 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [7 s]: openapi-document/component-modifiers - END [0.04 s]
DEBUG [7 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [7 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [7 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [7.01 s]: openapi-document/profile-filter - END [0 s]
DEBUG [7.01 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [7.01 s]: openapi-document/emitter - START inputs = 1
DEBUG [7.04 s]: openapi-document/emitter - END [0.03 s]
DEBUG [7.88 s]: openapi-document/model-deduplicator - END [0.87 s]
DEBUG [7.88 s]: openapi-document/compose - START inputs = 1
DEBUG [8.72 s]: openapi-document/compose - END [0.84 s]
DEBUG [8.73 s]: openapi-document/identity - START inputs = 1
DEBUG [8.73 s]: openapi-document/identity - END [0 s]
[8.73 s] Clearing Folders.
[8.73 s] Writing Outputs.
[8.73 s] Generation Complete
[8.73 s] Shutting Down.
[8.74 s] Exiting.
```

Nothing generated even if output say so.

**Comment by kant2002** [comment] 2020-12-21 12:53
With last working version
```
> autorest --version=3.0.5537 --debug

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.0.6322; node: v15.2.1, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
Network Enabled: true
Starting @autorest/core from C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5537
   Loading AutoRest core      'C:\Users\user\.autorest\@microsoft.azure_autorest-core@3.0.5537\node_modules\@microsoft.azure\autorest-core\dist' (3.0.5537)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.82)
   Loading AutoRest extension '@microsoft.azure/autorest.typescript' (~2.0.12->2.0.683)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.51->2.3.51)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
DEBUG [10.54 s]: swagger-document/loader-swagger - START inputs = 0
DEBUG [10.54 s]: openapi-document-override/md-override-loader-openapi - START inputs = 0
DEBUG [10.54 s]: openapi-document/loader-openapi - START inputs = 0
DEBUG [10.55 s]: swagger-document-override/md-override-loader-swagger - START inputs = 0
DEBUG [10.55 s]: pipeline-emitter - START inputs = 0
DEBUG [10.59 s]: configuration-emitter - START inputs = 0
DEBUG [10.68 s]: pipeline-emitter - END [0.13 s]
DEBUG [10.68 s]: configuration-emitter - END [0.13 s]
DEBUG [11.08 s]: openapi-document-override/md-override-loader-openapi - END [0.53 s]
DEBUG [11.08 s]: swagger-document-override/md-override-loader-swagger - END [0.53 s]
DEBUG [11.22 s]: swagger-document/loader-swagger - END [0.68 s]
DEBUG [11.22 s]: swagger-document/individual/transform - SKIPPING
DEBUG [11.22 s]: swagger-document/individual/schema-validator-swagger - SKIPPING
DEBUG [11.23 s]: swagger-document/identity - SKIPPING
DEBUG [11.23 s]: swagger-document/individual/identity - SKIPPING
DEBUG [11.24 s]: openapi-document/openapi-document-converter - SKIPPING
DEBUG [11.5 s]: openapi-document/loader-openapi - END [0.95 s]
DEBUG [11.5 s]: openapi-document/individual/transform - START inputs = 1
DEBUG [11.54 s]: openapi-document/individual/transform - END [0.04 s]
DEBUG [11.54 s]: openapi-document/individual/schema-validator-openapi - START inputs = 1
DEBUG [11.69 s]: openapi-document/individual/schema-validator-openapi - END [0.15 s]
DEBUG [11.69 s]: openapi-document/individual/identity - START inputs = 1
DEBUG [11.69 s]: openapi-document/individual/identity - END [0 s]
DEBUG [11.69 s]: openapi-document/transform-immediate - START inputs = 2
DEBUG [11.73 s]: openapi-document/transform-immediate - END [0.03 s]
DEBUG [11.73 s]: openapi-document/transform - START inputs = 1
DEBUG [16.62 s]: openapi-document/transform - END [4.89 s]
DEBUG [16.62 s]: openapi-document/tree-shaker - START inputs = 1
DEBUG [16.86 s]: openapi-document/tree-shaker - END [0.23 s]
DEBUG [16.86 s]: openapi-document/multi-api-merger - START inputs = 1
DEBUG [17.18 s]: openapi-document/multi-api-merger - END [0.32 s]
DEBUG [17.18 s]: openapi-document/components-cleaner - START inputs = 1
DEBUG [17.54 s]: openapi-document/components-cleaner - END [0.35 s]
DEBUG [17.54 s]: openapi-document/component-modifiers - START inputs = 1
DEBUG [17.54 s]: openapi-document/component-modifiers - END [0 s]
DEBUG [17.54 s]: openapi-document/api-version-parameter-handler - START inputs = 1
DEBUG [17.55 s]: openapi-document/api-version-parameter-handler - END [0 s]
DEBUG [17.55 s]: openapi-document/profile-filter - START inputs = 1
DEBUG [17.55 s]: openapi-document/profile-filter - END [0 s]
DEBUG [17.55 s]: openapi-document/model-deduplicator - START inputs = 1
DEBUG [17.55 s]: openapi-document/emitter - START inputs = 1
DEBUG [17.56 s]: openapi-document/emitter - END [0.01 s]
DEBUG [19.2 s]: openapi-document/model-deduplicator - END [1.65 s]
DEBUG [19.2 s]: openapi-document/compose - START inputs = 1
DEBUG [19.52 s]: openapi-document/compose - END [0.31 s]
DEBUG [19.52 s]: openapi-document/identity - START inputs = 1
DEBUG [19.52 s]: openapi-document/identity - END [0 s]
DEBUG [19.52 s]: csharp/imodeler1 - START inputs = 1
DEBUG [19.52 s]: typescript/imodeler1 - START inputs = 1
DEBUG [23.07 s]: typescript/imodeler1 - END [3.55 s]
DEBUG [23.07 s]: typescript/commonmarker - START inputs = 1
DEBUG [23.53 s]: typescript/commonmarker - END [0.45 s]
DEBUG [23.53 s]: typescript/cm/transform - START inputs = 1
DEBUG [23.53 s]: typescript/cm/transform - END [0 s]
DEBUG [23.53 s]: typescript/cm/emitter - START inputs = 1
DEBUG [23.53 s]: typescript/generate - START inputs = 1
DEBUG [23.57 s]: typescript/cm/emitter - END [0.04 s]
DEBUG [23.58 s]: csharp/imodeler1 - END [4.05 s]
DEBUG [23.58 s]: csharp/commonmarker - START inputs = 1
DEBUG [24.13 s]: csharp/commonmarker - END [0.55 s]
DEBUG [24.14 s]: csharp/cm/transform - START inputs = 1
DEBUG [24.14 s]: csharp/cm/transform - END [0 s]
DEBUG [24.14 s]: csharp/generate - START inputs = 1
DEBUG [24.14 s]: csharp/cm/emitter - START inputs = 1
DEBUG [24.18 s]: csharp/cm/emitter - END [0.03 s]
INFORMATION: The output folder doesn't contain a pre-existing package.json file to get the package version from.
DEBUG [28.01 s]: Generating Rest Code
DEBUG [28.01 s]: Defaulting to generate client side Code
DEBUG [28.02 s]: [WRITING] ServiceClientTemplate => xxxAPI.cs
DEBUG [28.2 s]: [WRITING] ServiceClientInterfaceTemplate => IxxxAPI.cs
DEBUG [28.22 s]: [WRITING] ExtensionsTemplate => xxxAPIExtensions.cs
DEBUG [28.27 s]: [WRITING] ModelTemplate => Models/...
DEBUG [28.35 s]: [WRITING] ServiceClientTemplate => lib/xxxxAPI.ts
DEBUG [28.35 s]: [WRITING] ModelTemplate => Models/....
DEBUG [28.51 s]: csharp/generate - END [4.37 s]
DEBUG [28.52 s]: csharp/simplifier - START inputs = 74
DEBUG [29.18 s]: [WRITING] ServiceClientContextTemplate => lib/xxxxAPIContext.ts
DEBUG [29.28 s]: [WRITING] ModelIndexTemplate => lib/models/index.ts
DEBUG [29.72 s]: [WRITING] MapperIndexTemplate => lib/models/mappers.ts
DEBUG [29.96 s]: [WRITING] ParameterTemplate => lib/models/parameters.ts
DEBUG [30.05 s]: typescript/generate - END [6.52 s]
DEBUG [30.05 s]: typescript/transform - START inputs = 5
DEBUG [30.07 s]: typescript/transform - END [0.02 s]
DEBUG [30.08 s]: typescript/emitter - START inputs = 5
DEBUG [30.08 s]: Emitting 'source-file-typescript' at file:///....
DEBUG [30.09 s]: typescript/emitter - END [0.01 s]
DEBUG [39.34 s]: csharp/simplifier - END [10.82 s]
DEBUG [39.34 s]: csharp/transform - START inputs = 74
DEBUG [39.39 s]: csharp/transform - END [0.04 s]
DEBUG [39.39 s]: csharp/emitter - START inputs = 74
DEBUG [39.39 s]: Emitting 'source-file-csharp' at file:///....
DEBUG [39.58 s]: csharp/emitter - END [0.18 s]
[39.58 s] Clearing Folders.
[39.58 s] Writing Outputs.
[39.74 s] Generation Complete
[39.74 s] Shutting Down.
[39.74 s] Exiting.
```

**Comment by kant2002** [comment] 2021-01-08 11:20
@daviwil can you take a look?

**Comment by timotheeguerin** [comment] 2021-03-12 19:06
@kant2002 are you still having the issue with the latest version? If so I believe this might just be an issue with your configuration, could you share it? how are you expecting the typescript generator to run?

**Comment by kant2002** [comment] 2021-03-14 16:50
@timotheeguerin This one specific error no longer appears.

**Comment by kant2002** [comment] 2021-03-14 17:17
I cannot express how much I thankful for somehow fix magically appear in latest Autorest

**Comment by kant2002** [comment] 2021-04-12 11:15
Issue re-appear again after I run `autorest --latest`.
```
> autorest

WARNING: AutoRest has not been tested with Node versions greater than v14.

AutoRest code generation utility [cli version: 3.1.4; node: v15.7.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      'C:\Users\user\.autorest\@autorest_core@3.2.4\node_modules\@autorest\core\dist' (3.2.4)
[7.43 s] Generation Complete
```

What can I do to start debugging this kind of issue? What is worrying me, is why it do not blowup if there some configuration error on my side.

**Comment by timotheeguerin** [comment] 2021-04-12 14:22
Hi @kant2002 is this related to the new issue you opened? Running with `--debug --verbose` will provide more information and could help figuring out what is going on. My guess is that here is the configuration is no loading any generators(as this log is showing). You can add `--output-artifact=configuration.yaml` that should output a configuration.yaml file and you can see the config that was resolved.

**Comment by kant2002** [comment] 2021-04-12 15:55
I think this is unrelated. I have no proof for that, just gut feeling based on my battle scars with Autorest.
I will look at `--output-artifact=configuration.yaml`. 
What if that's the case I add some reporting  that "no-generators" found. At least it would be a step in proper direction for me and somebody who maybe hit same kind of issues. I would really like think that UX of such amazing tool can be improved .

**Comment by timotheeguerin** [comment] 2021-04-12 16:18
When reproducing this issue, do you have anywhere in your config or in the command line a reference to one of the generators?
If not this is expected.

**Comment by kant2002** [comment] 2021-04-12 16:28
- I use plain `autorest` command
- I do not have `use-extension` in that MD file anywhere when I test that.

**Comment by timotheeguerin** [comment] 2021-04-12 16:31
Yeah so then that would be expected, if you are not specifying what you want to generate autorest won't generate anything. 
Now maybe something could be done to warn the user that nothing is happening because of that but due to the flexibility of autorest this can be tricky to know if it actually doesn't do what the user want

**Comment by kant2002** [comment] 2021-04-12 16:32
Why it was working before, I have configuration like that 
```
csharp:
 - output-directory: Xx
typescript:
 - output-directoyr: yy
```
and it produce both variants when I run `autorest`.

**Comment by kant2002** [comment] 2021-04-12 16:38
I probably incorrectly interpret that you ask about command line only. I correctly have `csharp` and `typescript` mentioned in configuration

**Comment by timotheeguerin** [comment] 2021-04-12 20:19
Closing, believe this was resolved in the other issue

**Closed by timotheeguerin** 2021-04-12 20:19 UTC
Labels: AutoRest v3, needs-author-feedback
