### ISSUE TITLE
[openapi-to-tsp] Node 20 produce different output for openai spec

### ISSUE THREAD

**Issue by timotheeguerin** [Azure/autorest#4795] opened 2023-11-15 18:28 UTC
AS part of upgrading dependencies and increaasing node versions noticed that in node 20 we get a different diff for openai spec. Some things become `unknown`

```

 model PathsMaorw9DeploymentsDeploymentIdCompletionsPostResponses200ContentApplicationJsonSchema {
   id?: string;
   object?: string;
@@ -189,7 +175,7 @@ model Paths13PiqocDeploymentsDeploymentIdEmbeddingsPostRequestbodyContentApplica
 An input to embed, encoded as a string, a list of strings, or a list of token
 lists
 """)
-  input: PostContentSchemaInput;
+  input: unknown;
 
   @doc("The ID of the end-user, for use in tracking and rate-limiting.")
   user?: string;
@@ -201,9 +187,3 @@ lists
   @doc("ID of the model to use")
   `model`?: string;
 }
-
-@doc("""
-An input to embed, encoded as a string, a list of strings, or a list of token
-lists
-""")
-model PostContentSchemaInput {}

```

**Comment by joheredi** [comment] 2024-01-22 20:57
Closing as I haven't been able to reproduce with the latest Node 20 version

**Comment by tadelesh** [comment] 2024-01-24 05:57
my env with node v18.16.0 or node v20.11.0 all could reproduce this. no idea the root cause.

**Comment by tadelesh** [comment] 2024-01-24 07:18
after upgrade core version and m4 version, this problem has been resolved. see: https://github.com/Azure/autorest/pull/4868.

**Closed by tadelesh** 2024-01-24 07:18 UTC
Labels: bug, Mgmt, openapi-to-tsp
