### ISSUE TITLE
Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.0'

### ISSUE THREAD

**Issue by Yitzchok** [Azure/autorest#3924] opened 2021-02-24 01:07 UTC
After doing `autorest --reset` no autorest extensions get installed

I tried with other versions of core and with and without NVS (with LTS and the latest versions of node).

I tried this with autorest@3.1.1 and autorest@3.0.6339

```
AutoRest code generation utility [cli version: 3.0.6339; node: v15.4.0, max-memory: 4096 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest

There is a new version of AutoRest available (3.1.1).
 > You can install the newer version with with npm install -g autorest@latest

Failure:
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.0'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.0.0'.
    at Object.selectVersion (C:\Program Files\nodejs\node_modules\autorest\dist\src\autorest-as-a-service.js:287:23)
    at processTicksAndRejections (node:internal/process/task_queues:93:5)
    at async main (C:\Program Files\nodejs\node_modules\autorest\dist\src\app.js:109:31)
```

Moved from https://github.com/Azure/autorest/issues/3919#issuecomment-784494510

**Comment by timotheeguerin** [comment] 2021-02-24 02:45
Closing as the root cause was found to be the same as #3925

**Closed by timotheeguerin** 2021-02-24 02:45 UTC
Labels: Bug
