### ISSUE TITLE
[C#] Object not beign serialized to JSON

### ISSUE THREAD

**Issue by MrBirdman** [Azure/autorest#1904] opened 2017-03-03 12:13 UTC
Objets are not beign serialized properly. Autorest generated client converts them into an empty JSON:

The following fragment returns _requestContent = {}

```
            // Serialize Request
            string _requestContent = null;
            if(addMpgEventWithRmVersionsAndStatusRequest != null)
            {
                _requestContent = Microsoft.Rest.Serialization.SafeJsonConvert.SerializeObject(addMpgEventWithRmVersionsAndStatusRequest, this.Client.SerializationSettings);
                _httpRequest.Content = new System.Net.Http.StringContent(_requestContent, System.Text.Encoding.UTF8);
                _httpRequest.Content.Headers.ContentType =System.Net.Http.Headers.MediaTypeHeaderValue.Parse("application/json; charset=utf-8");
            }
```

Eveything works fine if i set 
`this.Client.SerializationSettings.ContractResolver = null`

Request model:
```
// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace NV.RangeManagement.WebApi.Client.Models
{
    using System.Linq;

    public partial class AddMPGEventWithRMVersionsAndStatusRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// AddMPGEventWithRMVersionsAndStatusRequest class.
        /// </summary>
        public AddMPGEventWithRMVersionsAndStatusRequest() { }

        /// <summary>
        /// Initializes a new instance of the
        /// AddMPGEventWithRMVersionsAndStatusRequest class.
        /// </summary>
        public AddMPGEventWithRMVersionsAndStatusRequest(string token = default(string), System.DateTime? dateCreated = default(System.DateTime?), System.DateTime? dateModified = default(System.DateTime?), System.DateTime? dateDeleted = default(System.DateTime?), string userName = default(string), int? subjectId = default(int?), string subject = default(string), int? siteId = default(int?), string action = default(string), string rmCreated = default(string), string rmUpdated = default(string), int? type = default(int?))
        {
            Token = token;
            DateCreated = dateCreated;
            DateModified = dateModified;
            DateDeleted = dateDeleted;
            UserName = userName;
            SubjectId = subjectId;
            Subject = subject;
            SiteId = siteId;
            Action = action;
            RmCreated = rmCreated;
            RmUpdated = rmUpdated;
            Type = type;
        }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Token")]
        public string Token { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DateCreated")]
        public System.DateTime? DateCreated { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DateModified")]
        public System.DateTime? DateModified { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "DateDeleted")]
        public System.DateTime? DateDeleted { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "UserName")]
        public string UserName { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SubjectId")]
        public int? SubjectId { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Subject")]
        public string Subject { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "SiteId")]
        public int? SiteId { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Action")]
        public string Action { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RmCreated")]
        public string RmCreated { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "RmUpdated")]
        public string RmUpdated { get; private set; }

        /// <summary>
        /// </summary>
        [Newtonsoft.Json.JsonProperty(PropertyName = "Type")]
        public int? Type { get; private set; }

    }
}
```

AutoRest Code Generator 0.17.0.0

EDIT: It seems the problem is with the properties beign readonly, when i've set a public setter everything serialized properly.

**Comment by olydis** [comment] 2017-03-14 02:43
Yes, read only properties are not serialized. The idea of `readOnly` is that these properties are really not writable *on the server*, i.e. it also makes no sense at all to serialize them in any request.

**Comment by olydis** [comment] 2017-03-14 02:44
will close this as this is by design

**Closed by olydis** 2017-03-14 02:44 UTC
