### ISSUE TITLE
Add code gen support for the "deprecated" tag

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1296] opened 2016-07-20 21:22 UTC
We need to have support for the deprecated tag in swagger for our code gen in order to easily and consistently mark APIs/methods/operations as deprecated prior to their removal.

**Comment by brjohnstmsft** [comment] 2016-07-20 21:38
Duplicate of: https://github.com/Azure/autorest/issues/1285

**Closed by brjohnstmsft** 2016-07-20 21:38 UTC
