### ISSUE TITLE
AutoRest - Can the Response have the actual exception details from API

### ISSUE THREAD

**Issue by ryk2** [Azure/autorest#2496] opened 2017-08-03 08:14 UTC
Hi,
Is there a way by which I can get the actual exception details occurred as part of the API call. It would be helpful if this could help us 
- to customize the retry mechanism based on the actual exception. We may retry it for some exceptions like timeout and we may not retry it for fatal data exceptions such as divided by zero or no data errors.
- to log the error in detail which would help us to find the issues in production easily.

Please suggest if there is anything existing or if we can implement this in future.

Thanks,
Yogesh

**Comment by olydis** [comment] 2017-08-03 16:56
Think this is a duplicate of #2022 which is rolled up in #2448. Note that we cannot change some of this (arguably bad) behavior since there might be code out there relying on that behavior. However, this is very high on our list of priorities in the future! Please reopen if I'm mistaken and feel free to add more information or wishes - I've added this issue to the rollup so we *will* look at it when implementing it.

**Closed by olydis** 2017-08-03 16:56 UTC

**Comment by olydis** [comment] 2017-08-03 17:01
By the way, I think some of the exceptions you mention already throw different types of `Exception` (divided by zero vs. anything cloud based) - so you may be able to filter on that at least as a first approximation... however, could well be that things like server timeout and actual errors sent by the server use the same exception class, but even then the message should be different. Maybe that helps until we get further.

**Comment by ryk2** [comment] 2017-08-04 09:01
Divided by Zero from the APi becomes "Operation returned an invalid status code 'InternalServerError'" to the consumer which could either be Web or another API. Hence it is always InternalServerError. Can you please let me know if we can capture the timeout exception exclusively if we specify something in the swagger.
