### ISSUE TITLE
Auto-generated model with "value" and "nextLink" property got flattened 

### ISSUE THREAD

**Issue by YingXue** [Azure/autorest#2905] opened 2018-04-24 19:40 UTC
Hi, auto rest and swagger experts,

I’d appreciate some help here.

I am having some trouble with the following model definition in the swagger:
    
```
  "IotHubQuotaMetricInfoListResult": {
        "description": "The JSON-serialized array of IotHubQuotaMetricInfo objects with a next link.",
        "type": "object",
        "properties": {
          "value": {
            "description": "The array of quota metrics objects.",
            "type": "array",
            "items": {
              "$ref": "#/definitions/IotHubQuotaMetricInfo"
            }
          },
          "nextLink": {
            "description": "The next link.",
            "type": "string",
            "readOnly": true
          }
        }
      }
```

When I run auto rest, the generate model looks like this: 

```
export interface IotHubQuotaMetricInfoListResult **extends Array<IotHubQuotaMetricInfo>** {
    /**
     * @member {string} [nextLink] The next link.
     */
    readonly nextLink?: string;
}
```

The “value” property is missing as you can see from the above, but I am expecting the following:

```
export interface IotHubQuotaMetricInfoListResult extends Array<IotHubQuotaMetricInfo> {
    /**
     * @member {IotHubQuotaMetricInfo[]} [value] The array of quota metrics
     * objects.
     */
    value?: IotHubQuotaMetricInfo[]; //TODO: how to properly add property with name "value"
    /**
     * @member {string} [nextLink] The next link.
     */
    readonly nextLink?: string;
}
```

The following is the api signature using the IotHubQuotaMetricInfoListResult definition:

```
"/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Devices/IotHubs/{resourceName}/quotaMetrics": {
      "get": {
       .. a lot of stuff here…
        "responses": {
          "200": {
            "description": "This is a synchronous operation. The response contains a JSON-serialized array of the quota metrics for the IoT hub.",
            "schema": {
              "$ref": "#/definitions/IotHubQuotaMetricInfoListResult"
            }
          },
          "default": {
            "description": "DefaultErrorResponse",
            "schema": {
              "$ref": "#/definitions/ErrorDetails"
            }
          }
        },
        "deprecated": false,
            "x-ms-pageable": {
                "nextLinkName": "nextLink"
            }
      }
    }
```
Any idea what is the issue here or if I can have a unflatted model in any way?

**Comment by deathly809** [comment] 2018-04-24 20:17
@YingXue Please provide the command you used to generated the SDK.

**Comment by deathly809** [comment] 2018-04-24 20:34
@YingXue  I cannot reproduce your error.  
```
autorest --input-file=Test.json --typescript 
```

```

/**
 * @interface
 * An interface representing IotHubQuotaMetricInfoListResult.
 * The JSON-serialized array of IotHubQuotaMetricInfo objects with a next link.
 *
 */
export interface IotHubQuotaMetricInfoListResult {
  /**
   * @member {IotHubQuotaMetricInfo[]} [value] The array of quota metrics
   * objects.
   */
  value?: IotHubQuotaMetricInfo[];
  /**
   * @member {string} [nextLink] The next link.
   */
  readonly nextLink?: string;
}
```

**Comment by YingXue** [comment] 2018-04-25 15:57
Thanks for the reply.
There is the yaml I used:

``` yaml
azure-arm: true
add-credentials: true
input-file:
  - swagger-04-01-preview-management.json

typescript:
  output-folder: ./generated/typescript
 
 ```

**Comment by deathly809** [comment] 2018-04-25 17:36
I have reproduced your output.  It is because of azure-arm: true.  Have you validated that the result does not have all the data?

**Comment by andrew-buckley** [comment] 2018-04-25 17:51
Hi @deathly809, what do you mean by validating that the result does not have all the data? You mean when we use the autorest generated operations, does that have the correct data returned for the IotHubQuotaMetricInfoListResult?

**Comment by andrew-buckley** [comment] 2018-04-25 17:52
Our goal here is to use the autorest generated models independently.

**Comment by deathly809** [comment] 2018-04-25 18:15
@andrew-buckley Have you validated that when you use the generated typescript that it does not work?  You can see that it converts the data into an array with an extra property called NextLink.  Have you validated that the array is empty or not correct in some way?  There is exactly one other typescript example in azure-api-rest-specs repo and it uses openapi-type: arm and not azure-arm: true.  

https://github.com/Azure/azure-rest-api-specs/blob/806bf8011e563e8a7cf69ee8eb9470126d8a2f64/specification/marketplaceordering/resource-manager/readme.md

**Comment by YingXue** [comment] 2018-04-26 17:40
Thank you for the response @deathly809, this "openapi-type: arm" parameter answers my call perfectly.

**Comment by deathly809** [comment] 2018-04-26 19:53
@YingXue Glad I could be of help.  So all issues are resolved?

**Comment by YingXue** [comment] 2018-04-27 00:14
Yes. Please feel free to close the issue. Thanks again.

**Comment by deathly809** [comment] 2018-04-27 15:48
@fearthecowboy Issue is resolved but I cannot close it.

**Closed** 2019-11-22 22:00 UTC
