### ISSUE TITLE
Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'

### ISSUE THREAD

**Issue by lima-msft** [Azure/autorest#3904] opened 2021-02-22 07:20 UTC
**Describe the bug**

Install latest autorest version and hit below failure. From https://github.com/Azure/autorest/releases, could not find 3.1.0 version for autorest-core
```
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'.
Error: Unable to find a valid AutoRest core package '@autorest/core' @ '~3.1.0'.
    at Object.selectVersion (C:\Users\li\AppData\Roaming\npm\node_modules\autorest\dist\src_autorest-as-a-service_ts-src_coloring_ts.js:297:23)
    at async main (C:\Users\li\AppData\Roaming\npm\node_modules\autorest\dist\app.js:213:31)
```

**Comment by timotheeguerin** [comment] 2021-02-22 16:25
duplicate of #3904

**Closed by timotheeguerin** 2021-02-22 16:25 UTC
Labels: Bug, duplicate

**Comment by poyyaren** [comment] 2021-02-22 19:27
> duplicate of #3904

you mean duplicate of #3899 ? Since #3904 is a self-reference....

**Comment by timotheeguerin** [comment] 2021-02-22 19:37
yes sorry, good catch
