### ISSUE TITLE
Generated HttpCompletionOption.ResponseHeadersRead line doesn't work with streams

### ISSUE THREAD

**Issue by MrLinDowsMac** [Azure/autorest#2108] opened 2017-04-03 23:59 UTC
In a web service, I have some actions that returns a stream (file). Autorest generates from swagger json methods with a signature like this: `public async Task<HttpOperationResponse<Stream>>`

In my client code I need a stream to read, but unfortunetly i get `System.NullReferenceException: Object reference not set to an instance of an object`. 

I already found that the problem is one line of the following generated code, in the **HttpCompletionOption**:
```
// Send Request
            if (_shouldTrace)
            {
                ServiceClientTracing.SendRequest(_invocationId, _httpRequest);
            }
            cancellationToken.ThrowIfCancellationRequested();
            _httpResponse = await Client.HttpClient.SendAsync(_httpRequest, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
            if (_shouldTrace)
```

If I change HttpCompletionOption.ResponseHeadersRead to HttpCompletionOption.ResponseContentRead it works properly and I can get my file.

I have this problem since Autorest 0.7.3 (from Nuget) but this also present in latest 0.9.22, so everytime I generate or update my client code I have to manually correct that line.

**Comment by olydis** [comment] 2017-04-04 16:57
Where is the NRE happening exactly? A minimum reproducing example (Swagger) could also helpful, as we do have test cases for streams that seem to work properly. Thanks! :-)

**Comment by MrLinDowsMac** [comment] 2017-04-04 21:27
@olydis Here it is an example. Let's suppose I have the following swagger metadata json:

```
{
  "swagger": "2.0",
  "info": {
    "version": "v1",
    "title": "Reportspdfservice"
  },
  "host": "mypdfservice.mycompany.com",
  "schemes": [
    "http"
  ],
  "paths": {
    "/api/production/OrderWithCosts/GetReport/{folio}": {
      "get": {
        "tags": [
          "Production"
        ],
        "operationId": "Production_ExportReport",
        "consumes": [],
        "produces": [
          "application/octet-stream"
        ],
        "parameters": [
          {
            "name": "folio",
            "in": "path",
            "required": true,
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "File Response",
            "schema": {
              "format": "byte",
              "type": "file"
            }
          }
        }
      }
    }
  },
  "definitions": {},
  "securityDefinitions": {
    "basic": {
      "type": "basic",
      "description": "Basic HTTP Authentication"
    }
  }
}
```

Autorest generates this class Production.cs file (in my project):

```
// Code generated by Microsoft (R) AutoRest Code Generator 0.17.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace AppConsuming.Pdfservice
{
    using Microsoft.Rest;

    /// <summary>
    /// Production operations.
    /// </summary>
    public partial class Production : Microsoft.Rest.IServiceOperations<Reportspdfservice>, IProduction
    {
        /// <summary>
        /// Initializes a new instance of the Production class.
        /// </summary>
        /// <param name='client'>
        /// Reference to the service client.
        /// </param>
        /// <exception cref="System.ArgumentNullException">
        /// Thrown when a required parameter is null
        /// </exception>
        public Production(Reportspdfservice client)
        {
            if (client == null) 
            {
                throw new System.ArgumentNullException("client");
            }
            this.Client = client;
        }

        /// <summary>
        /// Gets a reference to the Reportspdfservice
        /// </summary>
        public Reportspdfservice Client { get; private set; }

        /// <param name='folio'>
        /// </param>
        /// <param name='customHeaders'>
        /// Headers that will be added to request.
        /// </param>
        /// <param name='cancellationToken'>
        /// The cancellation token.
        /// </param>
        /// <exception cref="Microsoft.Rest.HttpOperationException">
        /// Thrown when the operation returned an invalid status code
        /// </exception>
        /// <exception cref="Microsoft.Rest.SerializationException">
        /// Thrown when unable to deserialize the response
        /// </exception>
        /// <exception cref="Microsoft.Rest.ValidationException">
        /// Thrown when a required parameter is null
        /// </exception>
        /// <return>
        /// A response object containing the response body and response headers.
        /// </return>
        public async System.Threading.Tasks.Task<Microsoft.Rest.HttpOperationResponse<System.IO.Stream>> ExportReportWithHttpMessagesAsync(string folio, System.Collections.Generic.Dictionary<string, System.Collections.Generic.List<string>> customHeaders = null, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            if (folio == null)
            {
                throw new Microsoft.Rest.ValidationException(Microsoft.Rest.ValidationRules.CannotBeNull, "folio");
            }
            // Tracing
            bool _shouldTrace = Microsoft.Rest.ServiceClientTracing.IsEnabled;
            string _invocationId = null;
            if (_shouldTrace)
            {
                _invocationId = Microsoft.Rest.ServiceClientTracing.NextInvocationId.ToString();
                System.Collections.Generic.Dictionary<string, object> tracingParameters = new System.Collections.Generic.Dictionary<string, object>();
                tracingParameters.Add("folio", folio);
                tracingParameters.Add("cancellationToken", cancellationToken);
                Microsoft.Rest.ServiceClientTracing.Enter(_invocationId, this, "ExportReport", tracingParameters);
            }
            // Construct URL
            var _baseUrl = this.Client.BaseUri.AbsoluteUri;
            var _url = new System.Uri(new System.Uri(_baseUrl + (_baseUrl.EndsWith("/") ? "" : "/")), "/api/production/OrderWithCosts/GetReport/{folio}").ToString();
            _url = _url.Replace("{folio}", System.Uri.EscapeDataString(folio));
            // Create HTTP transport objects
            System.Net.Http.HttpRequestMessage _httpRequest = new System.Net.Http.HttpRequestMessage();
            System.Net.Http.HttpResponseMessage _httpResponse = null;
            _httpRequest.Method = new System.Net.Http.HttpMethod("GET");
            _httpRequest.RequestUri = new System.Uri(_url);
            // Set Headers
            if (customHeaders != null)
            {
                foreach(var _header in customHeaders)
                {
                    if (_httpRequest.Headers.Contains(_header.Key))
                    {
                        _httpRequest.Headers.Remove(_header.Key);
                    }
                    _httpRequest.Headers.TryAddWithoutValidation(_header.Key, _header.Value);
                }
            }

            // Serialize Request
            string _requestContent = null;
            // Set Credentials
            if (this.Client.Credentials != null)
            {
                cancellationToken.ThrowIfCancellationRequested();
                await this.Client.Credentials.ProcessHttpRequestAsync(_httpRequest, cancellationToken).ConfigureAwait(false);
            }
            // Send Request
            if (_shouldTrace)
            {
                Microsoft.Rest.ServiceClientTracing.SendRequest(_invocationId, _httpRequest);
            }
            cancellationToken.ThrowIfCancellationRequested();
            _httpResponse = await this.Client.HttpClient.SendAsync(_httpRequest, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);
            if (_shouldTrace)
            {
                Microsoft.Rest.ServiceClientTracing.ReceiveResponse(_invocationId, _httpResponse);
            }
            System.Net.HttpStatusCode _statusCode = _httpResponse.StatusCode;
            cancellationToken.ThrowIfCancellationRequested();
            string _responseContent = null;
            if ((int)_statusCode != 200)
            {
                var ex = new Microsoft.Rest.HttpOperationException(string.Format("Operation returned an invalid status code '{0}'", _statusCode));
                if (_httpResponse.Content != null) {
                    _responseContent = await _httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false);
                }
                else {
                    _responseContent = string.Empty;
                }
                ex.Request = new Microsoft.Rest.HttpRequestMessageWrapper(_httpRequest, _requestContent);
                ex.Response = new Microsoft.Rest.HttpResponseMessageWrapper(_httpResponse, _responseContent);
                if (_shouldTrace)
                {
                    Microsoft.Rest.ServiceClientTracing.Error(_invocationId, ex);
                }
                _httpRequest.Dispose();
                if (_httpResponse != null)
                {
                    _httpResponse.Dispose();
                }
                throw ex;
            }
            // Create Result
            var _result = new Microsoft.Rest.HttpOperationResponse<System.IO.Stream>();
            _result.Request = _httpRequest;
            _result.Response = _httpResponse;
            // Deserialize Response
            if ((int)_statusCode == 200)
            {
                _result.Body = await _httpResponse.Content.ReadAsStreamAsync().ConfigureAwait(false);
            }
            if (_shouldTrace)
            {
                Microsoft.Rest.ServiceClientTracing.Exit(_invocationId, _result);
            }
            return _result;
        }

  }
}

```

But As I said, only by changing  `_httpResponse = await this.Client.HttpClient.SendAsync(_httpRequest, System.Net.Http.HttpCompletionOption.ResponseHeadersRead, cancellationToken).ConfigureAwait(false);` 
to ` _httpResponse = await this.Client.HttpClient.SendAsync(_httpRequest, System.Net.Http.HttpCompletionOption.ResponseContentRead, cancellationToken).ConfigureAwait(false);` works for me

**Comment by olydis** [comment] 2017-04-04 22:04
thanks!

**Comment by olydis** [comment] 2017-04-04 22:31
The thing is: We *have* to generate `System.Net.Http.HttpCompletionOption.ResponseHeadersRead` here. `ResponseContentRead` will make the call blocking until the entire data (could be gigabytes) has arrived! With streams, the idea is exactly the opposite: Return ASAP, make the data accessible using the stream as it arrives.

So where is the NullReferenceException thrown? `SendAsync`?

**Comment by MrLinDowsMac** [comment] 2017-04-05 15:23
No, it is somewhere else. With HttpCompletionOption.ResponseContentRead, In my Xamarin project I just need to do the following:

```
Task<Microsoft.Rest.HttpOperationResponse<System.IO.Stream>> taskGetReport = production.ExportReportWithHttpMessagesAsync(txtFolio.Text);

Microsoft.Rest.HttpOperationResponse result = await taskGetReport;
reportPDF.BindingContext = result.Body;
await Navigation.PushAsync(reportPDF);
```
...

Then in reportPDF class:
```
base.OnAppearing();
Stream stream = new MemoryStream();
            stream = BindingContext as MemoryStream;
            try
            {
                pdfViewerControl.LoadDocument(stream);
            }
```

So, with HttpCompletionOption.ResponseHeadersRead I get NullReferenceException in my code because the Body is empty.

**Comment by olydis** [comment] 2017-04-05 15:54
> the Body is empty

What does that mean? Is `result.Body == null`?
I see another huge issue: `result.Body` is not a `MemoryStream`, so when you say `BindingContext as MemoryStream`, I *expect* the result (variable `stream`) to be `null`!
What happens if you say `stream = BindingContext as Stream;`?

To help you further, please be precise: What does "empty" mean? Which variables are `null` in the code you posted? *Where* does the NRE happen?

**Comment by MrLinDowsMac** [comment] 2017-04-05 18:35
> I see another huge issue: result.Body is not a MemoryStream, so when you say BindingContext as MemoryStream, I expect the result (variable stream) to be null!
What happens if you say stream = BindingContext as Stream;?

Perhaps, but it works somehow when I change to HttpCompletionOption.ResponseContentRead.

> Which variables are null in the code you posted? Where does the NRE happen?

I inspected more carefully:
reportPDF.BindingContext = result.Body;

**result.Body:**
```
{System.Net.WebConnectionStream}
    base: {System.IO.Stream}
    CanRead: true
    CanSeek: false
    CanTimeout: true
    CanWrite: false
    Length: 33873
    Position: System.NotSupportedException: Specified method is not supported.
    ReadTimeout: 300000
    WriteTimeout: 300000
```

But in reportPDF, stream **is null**;
```
Stream stream = new MemoryStream();
stream = BindingContext as MemoryStream; // This line should overwrite it, but it doesn't. it is null.
```

But when I set ResponseContentRead, this happens when I inspect result.Body:
```
?result.Body
{System.IO.MemoryStream}
    base: {System.IO.Stream}
    CanRead: true
    CanSeek: true
    CanWrite: false
    Capacity: 33848
    Length: 33848
    Position: 0
```

And in reportPDF, after  `stream = BindingContext as MemoryStream; ` line:

```
?stream
{System.IO.MemoryStream}
    base: {System.IO.Stream}
    CanRead: true
    CanSeek: true
    CanWrite: false
    Capacity: 33848
    Length: 33848
    Position: 0
```

**Comment by olydis** [comment] 2017-04-12 15:40
> but it works somehow when I change to `HttpCompletionOption.ResponseContentRead`

It works because then the runtime reads everything into a buffer and then gives you a stream on that. This is not possible (and not desired!) in the other case, so it gives you a raw `WebConnectionStream`.

> But in reportPDF, `stream` is null

Perfect, then it's precisely for the reason I assumed before. The problem is completely unrelated to the generated code, all you have to do is *not* trying to convert a `WebConnectionStream` to a `MemoryStream` (*this* is what yields `null`). 

As suggested earlier:

> What happens if you say `stream = BindingContext as Stream;`?

That should fix your issue. I'll close this issue as everything is working as intended and expected.
Feel free to ask further clarifying questions on this thread :-)

**Closed by olydis** 2017-04-12 15:40 UTC
