### ISSUE TITLE
Documentation: Link to C# "how to use the generated client" is HTTP 404

### ISSUE THREAD

**Issue by CaiusJard** [Azure/autorest#3942] opened 2021-03-02 18:17 UTC
Go to docs, step 5 "how to use the generated client", leads to here:

https://github.com/Azure/autorest/blob/master/docs/client/readme.md

Click C#

-> HTTP 404

**Comment by timotheeguerin** [comment] 2021-03-02 19:23
Duplicate of https://github.com/Azure/autorest/issues/3836

We are in the process of rewritting docs. Those links were added as placeholder for where the docs will be. You can see the progress in that PR Azure/autorest.csharp#962

**Closed by timotheeguerin** 2021-03-02 19:23 UTC
Labels: Bug
