### ISSUE TITLE
Generated C# client class is public by default even when --public-clients=false is specified

### ISSUE THREAD

**Issue by Y-Sindo** [Azure/autorest#4019] opened 2021-03-26 06:07 UTC
Before asking the question:
- [x] have you checked the documentation in the [docs folder(https://github.com/Azure/autorest/tree/master/docs) and couldn't find the information there
- [x] have you checked existing issues for a similar question?

### AutoRest version 
```
> autorest --list-installed
AutoRest code generation utility [cli version: 3.1.3; node: v13.14.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest


Showing All Installed Extensions

 Type       Extension Name                           Version      Location
 core       @autorest/core                           3.0.6349   .autorest\@autorest_core@3.0.6349
 core       @autorest/core                           3.2.1      .autorest\@autorest_core@3.2.1
 core       @microsoft.azure/autorest-core           2.0.4417     .autorest\@microsoft.azure_autorest-core@2.0.4417
 extension  @microsoft.azure/autorest.csharp         2.3.91       
\.autorest\@microsoft.azure_autorest.csharp@2.3.91
 extension  @microsoft.azure/autorest.modeler        2.3.55       
\.autorest\@microsoft.azure_autorest.modeler@2.3.55
 extension  @microsoft.azure/classic-openapi-validator 1.0.14       .autorest\@microsoft.azure_classic-openapi-validator@1.0.14
 extension  @microsoft.azure/openapi-validator       1.0.4       .autorest\@microsoft.azure_openapi-validator@1.0.4
```

### Environment
```
AutoRest code generation utility [cli version: 3.1.3; node: v12.19.1, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '$USERHOME\.autorest\@autorest_core@3.2.1\node_modules\@autorest\core\dist' (3.2.1)
   Loading AutoRest extension '@microsoft.azure/autorest.csharp' (~2.3.79->2.3.91)
   Loading AutoRest extension '@microsoft.azure/autorest.modeler' (2.3.55->2.3.55)
[9.46 s] Generation Complete
```

### Command 
```ps1
autorest --csharp --public-clients=false --v3 readme.md
```

### Readme file

``` yaml
input-file: https://github.com/vicancy/azure-rest-api-specs/blob/f5333e775482e72ffdc91a9c545857bde39c5dad/specification/signalr/data-plane/AzureSignalR/preview/2020-10-01/azuresignalr.json
```

``` yaml $(csharp)
license-header: MICROSOFT_MIT_NO_VERSION
override-client-name: SignalRServiceRestClient
namespace: Microsoft.Azure.SignalR
output-folder: Generated
add-credentials: true
use-internal-constructors: true
```

**Comment by timotheeguerin** [comment] 2021-03-26 15:26
Hi @Y-Sindo can you add this to your readme
```yaml
output-artifact:
 - configuration.yaml
```
This should result in a `configuration.yaml` file created in your output directory and you can double check autorest understood the flag.

![image](https://user-images.githubusercontent.com/1031227/112654701-e5bc3280-8e0c-11eb-85bc-1b1038328edd.png)

If it did then its probably some issue with the csharp generator otherwise might be somthing in autorest or some misconfiguration

**Comment by Y-Sindo** [comment] 2021-03-31 06:39
@timotheeguerin I don't find this flag `public-clients` in the generated yml file. So I doubt that my AutoRest version is not up to date. I ran `autorest --reset` and then `autorest --v3 --csharp readme.md`, got the following output.
```
AutoRest code generation utility [cli version: 3.1.3; node: v13.14.0, max-memory: 2048 MB]
(C) 2018 Microsoft Corporation.
https://aka.ms/autorest
   Loading AutoRest core      '$USERHOME\.autorest\@autorest_core@3.0.6375\node_modules\@autorest\core\dist' (3.0.6375)
Failed to install or start extension '@autorest/csharp' (latest)
  TypeError: Cannot read property 'startsWith' of undefined
```

**Comment by timotheeguerin** [comment] 2021-03-31 15:41
When using `--legacy` it should load the old csharp package `@microsoft.azure/autorest.csharp` but here as you specified `--use:@autorest/csharp` it didn't and use that instead.

Are you saying that now the client generate as `internal` as expected but you couldn't see `public-clients: false` in `configuration.yaml`?

**Comment by Y-Sindo** [comment] 2021-04-01 03:41
No, I can't generate `internal` legacy client.

**Comment by timotheeguerin** [comment] 2021-04-01 05:09
Could you share the link to the readme file you are using?

**Comment by Y-Sindo** [comment] 2021-04-01 05:40
https://github.com/Azure/azure-signalr/blob/34af67e8a71eed1607f197c6631eb35e880d87e1/src/Microsoft.Azure.SignalR.Common/RestClients/readme.md

The readme file is on the issue description too.

**Comment by timotheeguerin** [comment] 2021-04-01 15:35
> The second try:
autorest --use:@autorest/csharp@3.0.0-beta.20210210.4 readme.md
This time @autorest/csharp was installed successfully, but I found the generated code was much different from the previous one, the generated client was internal but public-clients was still not found.

This I believe would have been expected(If this is the full command you used), it used the generator v3 and default to public-clients: false which doesn't get written to the config 

For this command

**Comment by timotheeguerin** [comment] 2021-04-14 20:02
HI @Y-Sindo have you figured out this issue?

**Comment by Y-Sindo** [comment] 2021-04-15 06:18
@timotheeguerin  `autorest --csharp --public-clients=false readme.md` This is still not working. I didn't try it on the other system. Do you have difficulty reproducing the problem with the README file posted?

**Comment by timotheeguerin** [comment] 2021-04-16 21:06
@Y-Sindo, no I am not able to reproduce.

**Comment by timotheeguerin** [comment] 2021-05-11 18:47
Closing, please reopen if you can reproduce on other systems.

**Closed by timotheeguerin** 2021-05-11 18:47 UTC
Labels: needs-author-feedback, question
