### ISSUE TITLE
Generating C# client with Windows Portable app ignores path parameters that reference parameters

### ISSUE THREAD

**Issue by Micteu** [Azure/autorest#2781] opened 2017-12-19 15:56 UTC
Running autorest-windows-portable-2.0.422 and using the csharp generator, if I have a parameter in a path that references a definition in the parameters section of the document, it is missing from the generated code. For example, if I have this:

      "parameters": {
        "AcceptLanguageHeaderRef": {
          "in": "header",
          "name": "Accept-Language-Ref",
          "type": "string",
          "description": "the language to return the results in",
          "required": false
        }

And further below in the paths I have this:

    "/ponies": {
      "get": {
        "summary": "gets a list of ponies",
        "operationId": "getPonyList",
        "parameters": [
          {
            "$ref": "#/parameters/AcceptLanguageHeaderRef"
          }

The resulting GetPonyListWithHttpMessagesAsync C# method is missing that parameter. I've attached a few files that demonstrate this. PonyApi.md is the config file used by AutoRest. ponySwagger.json is the Swagger doc that has two parameters that work (defined inline) and two that do not (referenced). Ponies.cs is one of the files generated by AutoRest.
[PonyFun.zip](https://github.com/Azure/autorest/files/1572247/PonyFun.zip)

**Comment by olydis** [comment] 2017-12-20 12:52
that is very odd - I'm OOF today, but I'll have this fixed on Thursday

**Comment by olydis** [comment] 2017-12-21 09:28
Ughhh, where was my head at, looking at the code you sent I realized that everything is in fact working as intended: When you declare parameters in the global `parameters` section, AutoRest interprets that as "those parameters are likely to stay the same across multiple calls, so make those *client parameters*". Indeed, you will find properties

``` C#

        /// <summary>
        /// the language to return the results in
        /// </summary>
        public string AcceptLanguageRef { get; set; }

        /// <summary>
        /// extra stuff
        /// </summary>
        public string QueryStuffRef { get; set; }
```

in the generated client, that are used by the `GetPonyListWithHttpMessagesAsync` method.

Of course, what you want to do is also supported, you just have to override the default behavior: Set ["x-ms-parameter-location": "method"](https://github.com/Azure/autorest/blob/master/docs/extensions/readme.md#x-ms-parameter-location) on the two parameters and everything should work as intended.

Will close as I assume this was the problem, but feel free to ask further questions or reopen if this doesn't work. 🙂

**Closed by olydis** 2017-12-21 09:28 UTC

**Comment by Micteu** [comment] 2017-12-21 14:31
Thanks! I was so focused on the method signature that I didn't look beyond it.
