### ISSUE TITLE
Node code gen does breaks enum constants

### ISSUE THREAD

**Issue by begoldsm** [Azure/autorest#1660] opened 2016-12-05 23:39 UTC
In node code gen does not properly enclose constant string values in single quotes. For example, this swagger snippet:
```
{
            "name": "syncFlag",
            "in": "query",
            "required": false,
            "type": "string",
            "default": "DATA",
            "description": "...",
            "enum": [
              "DATA",
              "METADATA",
              "CLOSE"
            ],
            "x-ms-enum": {
            "name": "SyncFlag",
            "modelAsString": false
            }
          },
```
Results in the following line of code in node (note the emphasis):
var syncFlag = (options && options.syncFlag !== undefined) ? **options.syncFlag : DATA;**

When it should result in DATA being enclosed ('DATA'):
var syncFlag = (options && options.syncFlag !== undefined) ? options.syncFlag : **'DATA';**

**Comment by begoldsm** [comment] 2016-12-05 23:40
@amarzavery FYI this is the issue for the node codegen for constants.

**Comment by olydis** [comment] 2016-12-29 19:57
Huh isn't this a duplicate of #1597!?

**Closed** 2016-12-29 20:24 UTC
Labels: nodejs
